In [1]:
import pandas as pd

In [2]:
la = pd.read_csv('/home/cmp/Downloads/ACORNLondon.csv')

In [3]:
la.shape

(178454, 15)

In [4]:
pd.Series(list(la.PostcodeSearch)).shape

(178454,)

In [5]:
pd.Series({i: j for i, j in enumerate(set(la.PostcodeSearch))}).shape

(178454,)

In [6]:
set(la.PostcodeSearch)

{'BR49QP',
 'BR49QQ',
 'BR49QR',
 'BR49QS',
 'BR49QT',
 'SE116HJ',
 'SE116HL',
 'SE116HS',
 'SE116HR',
 'BR49QD',
 'BR49QE',
 'BR49QF',
 'BR49QG',
 'BR49QH',
 'SE96HR',
 'BR49QJ',
 'SE116HX',
 'BR49QN',
 'W49ET',
 'W49EP',
 'W49EZ',
 'W49EN',
 'SE57FH',
 'SE57FJ',
 'SE57FA',
 'SE57FB',
 'SE57FD',
 'SE57FG',
 'SW193UN',
 'SW161LG',
 'SW161LF',
 'SW161LE',
 'SW161LD',
 'SW161LB',
 'SW161LA',
 'TW34LP',
 'SW161LN',
 'TW34LR',
 'SW161LL',
 'TW34LT',
 'SW161LJ',
 'SW161LH',
 'SW161LW',
 'TW34LJ',
 'SW161LS',
 'SW161LR',
 'SW161LQ',
 'SW161LP',
 'TW34LA',
 'TW34LB',
 'TW34LD',
 'SW161LZ',
 'SW161LY',
 'TW34LG',
 'EC3M7DX',
 'SE116HU',
 'SE116HT',
 'EC3M7DQ',
 'SE116HY',
 'RM82RX',
 'RM82RU',
 'RM82RP',
 'RM82RS',
 'RM82RR',
 'RM82RL',
 'RM82RN',
 'RM82RH',
 'RM82RJ',
 'RM82RE',
 'RM82RD',
 'RM82RG',
 'RM82RA',
 'RM82RB',
 'SE119AW',
 'EC1P1GU',
 'SE119AS',
 'EC1P1GL',
 'SE119AL',
 'EC1P1GJ',
 'EC1P1GH',
 'EC1P1GF',
 'SE119AF',
 'EC1P1GB',
 'W114HE',
 'EN54SN',
 'NW72AA',
 'DA163NN',
 'DA163NL',
 'DA163NJ',
 'DA163NH',
 'DA163NF',
 'DA163NG',
 'DA163ND',
 'DA163NE',
 'DA163NB',
 'DA163NA',
 'DA163NZ',
 'DA163NX',
 'DA163NY',
 'DA163NW',
 'DA163NT',
 'DA163NU',
 'DA163NR',
 'DA163NS',
 'DA163NP',
 'DA163NQ',
 'N80ED',
 'EN19NL',
 'HA27BT',
 'UB89SJ',
 'EN20TZ',
 'W84EA',
 'W84EB',
 'W84EE',
 'W84ED',
 'W84EG',
 'W84EF',
 'W84EH',
 'W84EQ',
 'W84EP',
 'W84EY',
 'W84EZ',
 'E112UB',
 'W1U8BF',
 'W1U8BE',
 'W1U8BD',
 'W1U8BB',
 'W1U8BA',
 'UB69PP',
 'W1U8BL',
 'W1U8BJ',
 'W1U8BH',
 'W1T4NA',
 'W1T4NB',
 'W1T4ND',
 'W1T4NE',
 'W1T4NF',
 'W1T4NG',
 'KT67UU',
 'TW134JQ',
 'KT67UW',
 'TW134JS',
 'KT67UQ',
 'TW134JU',
 'TW134JW',
 'TW134JX',
 'TW134JY',
 'TW134JZ',
 'KT67UD',
 'KT67UG',
 'KT67UA',
 'TW134JE',
 'KT67UB',
 'KT67UL',
 'TW134JJ',
 'KT67UN',
 'TW134JL',
 'KT67UH',
 'TW134JN',
 'KT67UJ',
 'IG26DX',
 'UB69PB',
 'SW166DF',
 'N134LH',
 'N134LJ',
 'N134LL',
 'N134LN',
 'N134LA',
 'N134LG',
 'N134LY',
 'N134LP',
 'N134LR',
 'N134LS',
 'N134LT',
 'N134LU',
 'TW34LX',
 'RM139TY',
 'RM139TX',
 'SW208YX',
 'TW34LY',
 'SW208YT',
 'RM139TR',
 'SW208YW',
 'SW208YP',
 'TW34LZ',
 'RM139TU',
 'RM139TT',
 'SW208YL',
 'RM139TH',
 'SW208YH',
 'RM139TB',
 'RM139TA',
 'SW208YG',
 'RM139TG',
 'SW208YB',
 'RM139TD',
 'TW34LQ',
 'RM14YH',
 'TW34LS',
 'RM14YL',
 'RM99LL',
 'W1H5EQ',
 'TW34LU',
 'RM14YY',
 'RM99LZ',
 'RM99LX',
 'W1H5ED',
 'W1H5EE',
 'W1H5EF',
 'TW34LW',
 'RM14YU',
 'W1H5EA',
 'W1H5EB',
 'TW34LH',
 'RM113JQ',
 'RM113JP',
 'RM113JS',
 'RM113JT',
 'RM113JW',
 'RM113JJ',
 'RM113JL',
 'RM113JN',
 'RM113JA',
 'TW34LL',
 'WC1B5BP',
 'RM113JB',
 'RM113JE',
 'RM113JD',
 'RM113JG',
 'RM113JF',
 'IG89EQ',
 'TW34LN',
 'IG89EY',
 'IG89EZ',
 'IG89EA',
 'IG89EB',
 'IG89EF',
 'IG89EG',
 'IG89EH',
 'IG89EJ',
 'IG89EL',
 'HA54SW',
 'CR94SA',
 'TW34LE',
 'TW34LF',
 'DA163AB',
 'SE280LW',
 'SE280LQ',
 'DA163AF',
 'HA22EN',
 'SE280LS',
 'DA163AD',
 'E1W9AF',
 'E1W9AN',
 'HA96QU',
 'DA163AH',
 'HA96QQ',
 'N229EN',
 'SE280LY',
 'SE280LX',
 'HA96QE',
 'HA96QD',
 'HA96QG',
 'HA96QF',
 'HA96QA',
 'HA96QB',
 'HA96QL',
 'DA163AL',
 'HA96QH',
 'HA96QJ',
 'SW152RN',
 'DA163AQ',
 'DA163AP',
 'SE280LA',
 'CR04XQ',
 'CR04XP',
 'CR04XS',
 'CR04XR',
 'CR04XU',
 'CR04XT',
 'CR04XY',
 'CR04XX',
 'CR04XZ',
 'CR04XA',
 'CR04XB',
 'NW101RQ',
 'CR04XD',
 'CR04XG',
 'CR04XF',
 'CR04XH',
 'CR04XJ',
 'CR04XL',
 'CR04XN',
 'IG110XU',
 'IG110XT',
 'IG110XW',
 'SE280LN',
 'IG110XQ',
 'IG110XP',
 'IG110XS',
 'IG110XR',
 'IG110XY',
 'IG110XZ',
 'IG110XE',
 'IG110XG',
 'IG110XF',
 'IG110XL',
 'IG110XN',
 'IG110XH',
 'IG110XJ',
 'SE42WE',
 'DA176JW',
 'DA176JP',
 'DA176JR',
 'DA176JS',
 'DA176JX',
 'DA176JY',
 'DA176JD',
 'DA176JE',
 'DA176JF',
 'DA176JG',
 'DA176JB',
 'DA176JL',
 'DA176JN',
 'DA176JJ',
 'SW154DE',
 'UB81DP',
 'UB81DQ',
 'W1A3JX',
 'UB81DX',
 'UB81DG',
 'UB81DB',
 'UB81DA',
 'UB81DJ',
 'E126PH',
 'E126PJ',
 'E126PL',
 'E126PN',
 'E126PA',
 'E126PB',
 'E126PG',
 'E126PX',
 'E126PY',
 'E126PZ',
 'E126PP',
 'E126PQ',
 'E126PR',
 'E126PS',
 'E126PT',
 'E126PU',
 'E126PW',
 'CR42EP',
 'CR42EQ',
 'CR42ER',
 'CR42ES',
 'CR42ET',
 'CR42EU',
 'SW112EX',
 'CR42EW',
 'CR42EX',
 'CR42EY',
 'CR42EZ',
 'SW112EU',
 'SW112ER',
 'SW112ES',
 'SW112EP',
 'SE93GX',
 'SW112EN',
 'CR42EA',
 'CR42EB',
 'SE93GD',
 'CR42ED',
 'CR42EE',
 'CR42EF',
 'CR42EG',
 'CR42EH',
 'SW112EG',
 'CR42EJ',
 'SW112EE',
 'CR42EL',
 'CR42EN',
 'E49AN',
 'SW154DU',
 'E49AL',
 'E49AJ',
 'SW166RW',
 'SW166RT',
 'SW166RU',
 'SW166RR',
 'SW166RS',
 'SW166RP',
 'SW166RQ',
 'EC1V7LW',
 'N66NT',
 'EC1V7LT',
 'W87XY',
 'N66NP',
 'SW166RX',
 'SW166RY',
 'SW166RF',
 'SW166RG',
 'SW166RE',
 'N66NH',
 'N66NJ',
 'SW166RN',
 'N66ND',
 'SW166RL',
 'SW166RJ',
 'SW166RH',
 'N66NB',
 'E49AE',
 'WC1R5EY',
 'WC1R5ET',
 'WC1R5EU',
 'WC1R5EF',
 'E49AA',
 'E49AZ',
 'EC4R0BE',
 'EC4R0BB',
 'EC4R0BL',
 'EC1P1GG',
 'TW74RW',
 'SE16AZ',
 'TW74RS',
 'SE16AP',
 'SE16AQ',
 'SE16AS',
 'SE16AT',
 'SE16AW',
 'TW74RF',
 'TW74RD',
 'TW74RE',
 'TW74RB',
 'SE16AN',
 'TW74RA',
 'TW74RN',
 'TW74RL',
 'TW74RJ',
 'TW74RH',
 'SE16AG',
 'SE193EE',
 'SE193ED',
 'SE193EG',
 'SE193EF',
 'SE193EB',
 'SE193EL',
 'SE193EN',
 'SE193EH',
 'SE193EJ',
 'SE193EU',
 'SE193ET',
 'SE193EW',
 'SE193EQ',
 'SE193ES',
 'SE193ER',
 'SE193EY',
 'SE193EX',
 'SE193EZ',
 'TW11XU',
 'TW11XS',
 'TW11XQ',
 'TW11XP',
 'TW11XB',
 'EN14UG',
 'SW1V1AA',
 'SW1V1AD',
 'SW47QA',
 'W1T2HD',
 'W1T2HE',
 'W1T2HF',
 'W1T2HG',
 'W1T2HA',
 'W1T2HB',
 'W1T2HL',
 'W1T2HN',
 'W1T2HW',
 'W1T2HP',
 'W1T2HQ',
 'W1T2HX',
 'W1T2HY',
 'W1T2HZ',
 'WC2A3SB',
 'W1C2AU',
 'SW1V1AN',
 'SW47QQ',
 'N181QL',
 'WC2A3SW',
 'BR20EQ',
 'WC2A3SU',
 'BR49JA',
 'BR69SS',
 'BR54ZB',
 'SE156RJ',
 'SW1P1EZ',
 'SE156RL',
 'SW1P1EX',
 'SE156RN',
 'SE156RA',
 'SW1P1EW',
 'SW1P1ET',
 'SE156RB',
 'SE156RE',
 'UB12NN',
 'SW1P1EP',
 'SE156RF',
 'SE156RY',
 'SE156RX',
 'SW1P1EL',
 'SW1P1EJ',
 'SW1P1EH',
 'SW1P1EF',
 'SE156RP',
 'SE156RS',
 'SE156RR',
 'SE156RU',
 'SE156RT',
 'SE156RW',
 'SW1P1EA',
 'NW64EF',
 'NW64EG',
 'NW64ED',
 'NW64EE',
 'NW64EB',
 'UB12NJ',
 'NW64EA',
 'NW64EN',
 'NW64EL',
 'NW64EJ',
 'NW64EH',
 'NW64EW',
 'NW64ET',
 'NW64EU',
 'NW64ER',
 'NW64ES',
 'NW64EP',
 'NW64EQ',
 'NW64EX',
 'NW64EY',
 'HA71DG',
 'HA71DD',
 'BR69SN',
 'HA71DB',
 'BR68JN',
 'N103QD',
 'BR68JL',
 'BR68JJ',
 'HA71DA',
 'BR68JH',
 'N103QB',
 'BR68JF',
 'BR68JG',
 'BR68JD',
 'BR68JE',
 'BR68JB',
 'N103QH',
 'BR68JA',
 'N103QU',
 'N103QT',
 'BR68JZ',
 'N103QP',
 'BR68JX',
 'BR68JY',
 'BR68JW',
 'BR68JT',
 'BR68JU',
 'BR68JR',
 'BR68JS',
 'BR68JP',
 'BR68JQ',
 'N88AD',
 'TN163AJ',
 'W1D3DT',
 'N88AG',
 'N88AA',
 'N88AL',
 'N88AN',
 'HA86RY',
 'HA71DJ',
 'N88AT',
 'N88AU',
 'N88AW',
 'N88AP',
 'N88AQ',
 'N88AR',
 'N88AS',
 'HA71DH',
 'N88AX',
 'N88AY',
 'N88AZ',
 'TW31SU',
 'TW31SW',
 'TW31SP',
 'TW31SQ',
 'TW31SR',
 'TW31SS',
 'SE171LN',
 'TW31SX',
 'HA71DU',
 'TW31SZ',
 'TW31SD',
 'TW31SE',
 'TW31SF',
 'TW31SG',
 'TW31SB',
 'TW31SL',
 'TW31SN',
 'TW31SJ',
 'SE109JU',
 'W44DW',
 'W44DT',
 'NW97JR',
 'W44DR',
 'SE109JP',
 'W44DP',
 'NW97JY',
 'NW97JX',
 'NW73AD',
 'NW73AE',
 'SE109JY',
 'SE109JX',
 'SE109JZ',
 'SE109JE',
 'SE109JG',
 'SE109JF',
 'SE109JA',
 'TN163AD',
 'NW97JG',
 'SE109JB',
 'W44DN',
 'SE109JL',
 'W44DL',
 'SE109JN',
 'W44DJ',
 'SE109JH',
 'W44DH',
 'NW97JN',
 'W120YX',
 'HA86RJ',
 'TN163AX',
 'HA86RH',
 'W1W6BS',
 'W1W6BR',
 'W87BA',
 'W87BG',
 'W87BE',
 'W87BD',
 'W87BJ',
 'W87BH',
 'W87BN',
 'W87BL',
 'W87BS',
 'W1W6BB',
 'W87BQ',
 'W87BP',
 'W1W6BF',
 'W87BU',
 'W1W6BD',
 'W87BY',
 'TN163AP',
 'SE255BA',
 'SE255BB',
 'SE255BE',
 'SE255BD',
 'SE255BG',
 'SE255BF',
 'SE255BH',
 'SE255BJ',
 'SE255BL',
 'SE255BN',
 'SE255BQ',
 'SE255BS',
 'SE255BU',
 'SE255BT',
 'SE255BW',
 'SE255BY',
 'SW1P9BG',
 'SE255BZ',
 'SW1P9BF',
 'NW61DW',
 'SW1P9BJ',
 'SE20HD',
 'SE20HE',
 'SE20HF',
 'SE20HG',
 'SE20HA',
 'SE20HB',
 'SE20HY',
 'SE20HZ',
 'SW1P9BW',
 'SE279AN',
 'SE279AJ',
 'SW1P9BU',
 'SE279AH',
 'SE279AF',
 'SE279AE',
 'SE279AA',
 'SE279AZ',
 'SE279AX',
 'SE279AW',
 'SE279AU',
 'SE279AR',
 'SE279AS',
 'SE279AP',
 'SE279AQ',
 'SE33DE',
 'SE33DF',
 'EN36WH',
 'SE33DH',
 'W1J9LE',
 'W1J9LL',
 'W1J9LN',
 'HA79HH',
 'N18HX',
 'N18HZ',
 'HA79HL',
 'HA79HA',
 'N18HW',
 'N18HP',
 'N18HQ',
 'N18HL',
 'HA79HZ',
 'N18HN',
 'N18HH',
 'N18HJ',
 'N18HD',
 'N18HE',
 'N18HF',
 'N18HG',
 'HA79HW',
 'N18HA',
 'N18HB',
 'HA79HT',
 'NW32EY',
 'NW32EX',
 'NW32ES',
 'NW32ER',
 'SE78DF',
 'NW32ET',
 'NW32EJ',
 'NW32EH',
 'NW32EL',
 'NW32EB',
 'NW32EA',
 'NW32EG',
 'NW32EF',
 'NW32EE',
 'NW32ED',
 'N228YW',
 'N228YT',
 'RM142SH',
 'N228YR',
 'RM142SJ',
 'N228YP',
 'EN53AX',
 'EN53AY',
 'EN53AZ',
 'N228YY',
 'N228YG',
 'N228YF',
 'N228YE',
 'N228YD',
 'RM142SX',
 'RM142SY',
 'RM142SZ',
 'EN53AG',
 'EN53AH',
 'RM142SU',
 'EN53AJ',
 'N228YL',
 'EN53AL',
 'RM142SQ',
 'EN53AN',
 'N228YH',
 'E179HE',
 'N111NA',
 'KT67EG',
 'IG110FD',
 'E112UA',
 'IG39RD',
 'IG39RE',
 'IG39RA',
 'IG39RB',
 'NW111FD',
 'IG39RN',
 'IG39RH',
 'IG39RJ',
 'IG39RT',
 'IG39RU',
 'IG39RW',
 'IG39RP',
 'IG39RQ',
 'IG39RS',
 'EN36WA',
 'IG39RX',
 'IG39RY',
 'IG39RZ',
 'NW43YA',
 'NW43YD',
 'E50LU',
 'EN36WB',
 'RM30UB',
 'RM30UA',
 'RM30UD',
 'RM30UJ',
 'RM30UH',
 'RM30UL',
 'RM30UR',
 'RM30UU',
 'RM30UT',
 'N111NF',
 'RM30UX',
 'W67AE',
 'W67AF',
 'W67AA',
 'W67AB',
 'W67AL',
 'W67AN',
 'W68GB',
 'HA14BN',
 'EN36WG',
 'W67AJ',
 'W68GY',
 'W67AU',
 'HA14BP',
 'W67AW',
 'W67AP',
 'HA14BW',
 'HA14BT',
 'W67AS',
 'HA14BZ',
 'HA14BX',
 'HA14BY',
 'HA88LJ',
 'HA88LH',
 'HA88LN',
 'HA88LL',
 'SW99UQ',
 'SW99UP',
 'HA88LA',
 'SW99UR',
 'SW99UU',
 'SW99UT',
 'HA88LE',
 'HA88LD',
 'SW99UH',
 'HA88LY',
 'HA88LX',
 'HA88LS',
 'HA88LR',
 'HA88LP',
 'HA88LW',
 'HA88LU',
 'HA88LT',
 'DA158ZA',
 'DA158ZB',
 'DA158ZD',
 'EN36WY',
 'E105DN',
 'DA158ZR',
 'SW166DT',
 'SE57TR',
 'E105DD',
 'E105DF',
 'TW134JP',
 'EN36WZ',
 'SE173LU',
 'SE173LX',
 'SE173LY',
 'SE173LZ',
 'TW134JR',
 'SE173LA',
 'SE173LE',
 'SE173LF',
 'UB111TD',
 'SE173LH',
 'TW134JT',
 'SE173LJ',
 'SE173LL',
 'E105DS',
 'E105DR',
 'BR12XU',
 'E105DU',
 'BR12XX',
 'E177PY',
 'BR12XE',
 'BR12XD',
 'N168RY',
 'E139WT',
 'N168RZ',
 'N168RP',
 'N168RS',
 'N168RR',
 'N168RW',
 'N168RH',
 'N168RJ',
 'N168RL',
 'SW184PL',
 'N168RN',
 'N168RA',
 'N168RE',
 'N168RG',
 'E139WJ',
 'SW100HT',
 'SW100HU',
 'E152QA',
 'SW100HP',
 'E152QG',
 'SW100HR',
 'SW100HS',
 'SW100HX',
 'TW134JB',
 'SW100HZ',
 'SW100HD',
 'SW100HE',
 'E152QQ',
 'SW100HA',
 'SW100HL',
 'SW100HN',
 'SW100HH',
 'SW100HJ',
 'SM44TS',
 'TW134JG',
 'SE182LW',
 'EN36WR',
 'BR20PX',
 'BR20PY',
 'BR20PZ',
 'BR20PT',
 'BR20PU',
 'BR20PW',
 'BR20PP',
 'BR20PQ',
 'BR20PR',
 'BR20PS',
 'BR20PL',
 'EN36WU',
 'BR20PN',
 'BR20PH',
 'BR20PJ',
 'BR20PD',
 'BR20PE',
 'BR20PF',
 'BR20PG',
 'BR20PA',
 'BR20PB',
 'SE182LG',
 'W84JP',
 'SE182LA',
 'SW165QT',
 'SW165QU',
 'SE187BY',
 'SW165QW',
 'SW165QP',
 'SW165QQ',
 'SW165QR',
 'SW165QS',
 'SE187BQ',
 'SW165QX',
 'SW165QY',
 'SW165QZ',
 'SW165QD',
 'SW165QE',
 'SW165QF',
 'SW165QG',
 'SW165QA',
 'SW165QB',
 'SE187BL',
 'SW165QL',
 'SE187BB',
 'SW165QN',
 'SE38AH',
 'SW165QJ',
 'SE187BD',
 'SE199BZ',
 'W93XD',
 'SE166QD',
 'W93XZ',
 'SE199BG',
 'SW166DW',
 'SW62LX',
 'SW62LT',
 'SW62LW',
 'SW62LP',
 'SW62LQ',
 'SW62LR',
 'SW62LL',
 'SW62LN',
 'SW62LH',
 'SW62LJ',
 'SW62LD',
 'SW62LE',
 'SW62LF',
 'SW62LG',
 'SW62LA',
 'SW62LB',
 'HA02YN',
 'BR11TD',
 'BR11TF',
 'BR11TG',
 'BR11TT',
 ...}

In [7]:
import geopandas as gpd

In [8]:
la

,Ward,PostcodeSearch,Lat,Long,Category,CategoryOrder,CategoryGroup,CategoryGroupOrder,CategoryType,CategoryTypeOrder,WellbeingGroup,WellbeingGroupOrder,WellbeingType,WellbeingTypeOrder,TotalPopulation
0,Darwin,TN162HY,51.293412,0.073846,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,14
1,Darwin,TN162HX,51.293948,0.061807,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,29
2,Darwin,TN162HU,51.294801,0.073564,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,7
3,Darwin,TN162HW,51.295155,0.054044,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,42
4,Coulsdon East,CR35QU,51.295447,-0.108488,Affluent Achiever,1,Mature Money,3,"Settled suburbia, older people",11,Caution,3,Countryside concerns,16,70
5,Coulsdon East,CR35QQ,51.295760,-0.107844,Affluent Achiever,1,Mature Money,3,"Settled suburbia, older people",11,Caution,3,Countryside concerns,16,39
6,Coulsdon East,CR35QS,51.295966,-0.108883,Affluent Achiever,1,Mature Money,3,"Settled suburbia, older people",11,Caution,3,Countryside concerns,16,26
7,Darwin,TN162JB,51.296103,0.083349,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,29
8,Darwin,TN162JE,51.296345,0.085884,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,44
9,Darwin,TN162JD,51.297715,0.085717,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Relishing retirement,19,10
10,Darwin,TN162JA,51.297740,0.076709,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,20
11,Coulsdon East,CR51DA,51.298248,-0.133935,Affluent Achiever,1,Mature Money,3,Better-off villagers,10,Healthy,4,Relishing retirement,19,21
12,Coulsdon East,CR51BU,51.298330,-0.124435,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,At Risk,2,Anxious adversity,11,53
13,Coulsdon East,CR51SX,51.298333,-0.108441,Affluent Achiever,1,Executive Wealth,2,Prosperous suburban families,8,Healthy,4,"Healthy, wealthy & wine",25,13
14,Coulsdon East,CR51BX,51.298369,-0.122985,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,Caution,3,Rooted routines,14,52
15,Coulsdon East,CR51BH,51.298412,-0.122266,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,At Risk,2,Anxious adversity,11,46
16,Coulsdon East,CR51PX,51.298575,-0.113954,Comfortable Communities,3,Successful Suburbs,7,Comfortably-off families in modern housing,24,Caution,3,Countryside concerns,16,17
17,Coulsdon East,CR51BT,51.298636,-0.120579,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,At Risk,2,Anxious adversity,11,81
18,Coulsdon East,CR51BR,51.298641,-0.126488,Urban Adversity,5,Struggling Estates,16,"Poorer families, many children, terraced housing",52,Health Challenges,1,Hardship heartlands,3,31
19,Darwin,TN162HR,51.298672,0.060656,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,28
20,Coulsdon East,CR51EE,51.298681,-0.117780,Financially Stretched,4,Poorer Pensioners,14,"Pensioners in social housing, semis and terraces",45,Health Challenges,1,Countryside complacency,5,23
21,Coulsdon East,CR51EP,51.298771,-0.114993,Comfortable Communities,3,Countryside Communities,6,Owner occupiers in small towns and villages,23,Health Challenges,1,Elderly ailments,4,19
22,Coulsdon East,CR51BW,51.298871,-0.121731,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,Caution,3,Rooted routines,14,8
23,Coulsdon East,CR51EQ,51.298904,-0.114270,Affluent Achiever,1,Mature Money,3,"Settled suburbia, older people",11,Caution,3,Countryside concerns,16,14
24,Darwin,TN162NS,51.298908,0.044600,Affluent Achiever,1,Executive Wealth,2,Well-off edge of towners,9,Healthy,4,Five-a-day greys,24,15
25,Coulsdon East,CR51DZ,51.299005,-0.123404,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,100
26,Coulsdon East,CR51DW,51.299228,-0.124356,Urban Adversity,5,Difficult Circumstances,17,"Singles and young families, some receiving ben...",58,Health Challenges,1,Hardship heartlands,3,24
27,Coulsdon East,CR51ER,51.299289,-0.114183,Comfortable Communities,3,Comfortable Seniors,9,"Older people, neat and tidy neighbourhoods",30,Health Challenges,1,Elderly ailments,4,31
28,Coulsdon East,CR51DY,51.299325,-0.122014,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,107
29,Coulsdon East,CR51BS,51.299338,-0.120048,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,Caution,3,Rooted routines,14,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178424,Turkey Street,EN88HT,51.682027,-0.047375,Comfortable Communities,3,Steady Neighbourhoods,8,"Owner occupied terraces, average income",28,Caution,3,Borderline behaviours,15,35
178425,Turkey Street,EN88RG,51.682028,-0.043657,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,100
178426,Turkey Street,EN88HS,51.682075,-0.045926,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,102
178427,Turkey Street,EN88RY,51.682109,-0.042569,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,57
178428,Turkey Street,EN88HP,51.682123,-0.045027,Urban Adversity,5,Difficult Circumstances,17,Deprived areas and high-rise flats,59,Health Challenges,1,Hardship heartlands,3,59
178429,Turkey Street,EN88RA,51.682146,-0.037793,Comfortable Communities,3,Steady Neighbourhoods,8,"Owner occupied terraces, average income",28,Caution,3,Borderline behaviours,15,42
178430,Turkey Street,EN88RB,51.682149,-0.040093,Comfortable Communities,3,Steady Neighbourhoods,8,"Owner occupied terraces, average income",28,Caution,3,Borderline behaviours,15,24
178431,Turkey Street,EN88HR,51.682221,-0.045500,Urban Adversity,5,Difficult Circumstances,17,Deprived areas and high-rise flats,59,Health Challenges,1,Limited living,1,20
178432,Chase,EN28BE,51.682237,-0.144648,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0
178433,Chase,EN29HR,51.682454,-0.089177,Affluent Achiever,1,Mature Money,3,Better-off villagers,10,Healthy,4,Relishing retirement,19,5
178434,Chase,EN29HW,51.682454,-0.089177,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,18
178435,Chase,EN29DG,51.682690,-0.098194,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0
178436,Chase,EN29ED,51.682853,-0.103265,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0
178437,Chase,EN29DJ,51.683248,-0.100456,Affluent Achiever,1,Executive Wealth,2,Asset rich families,4,Healthy,4,Relishing retirement,19,6
178438,Chase,EN29DX,51.683281,-0.104144,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0
178439,Chase,EN29DN,51.683543,-0.103684,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,8
178440,Chase,EN28AN,51.683609,-0.135304,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,7
178441,Chase,EN29DZ,51.684038,-0.099251,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,21
178442,Chase,EN29DR,51.684063,-0.104154,Affluent Achiever,1,Mature Money,3,Retired and empty nesters,12,Healthy,4,Sensible seniors,21,2
178443,Chase,EN29DP,51.684083,-0.100899,Comfortable Communities,3,Countryside Communities,6,Larger families in rural areas,22,Healthy,4,Relishing retirement,19,3
178444,Chase,EN28BA,51.684256,-0.111090,Affluent Achiever,1,Mature Money,3,Better-off villagers,10,Healthy,4,Relishing retirement,19,5
178445,Chase,EN28AY,51.684257,-0.108949,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Relishing retirement,19,2
178446,Chase,EN28AZ,51.684327,-0.109380,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Relishing retirement,19,7
178447,Chase,EN29DS,51.684394,-0.105674,Comfortable Communities,3,Countryside Communities,6,Larger families in rural areas,22,Caution,3,Countryside concerns,16,14
178448,Chase,EN29DW,51.684394,-0.105674,Affluent Achiever,1,Executive Wealth,2,Asset rich families,4,Healthy,4,Relishing retirement,19,2
178449,Chase,EN29EE,51.684394,-0.105674,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0
178450,Chase,EN65QT,51.684835,-0.158878,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,13
178451,Chase,EN29DY,51.685128,-0.098815,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,11
178452,Chase,EN29AX,51.685433,-0.098238,Rising Prosperity,2,Career Climbers,5,Mixed metropolitan areas,20,Healthy,4,Gym & juices,22,28
178453,Chase,EN29DU,51.688310,-0.105945,Affluent Achiever,1,Mature Money,3,Better-off villagers,10,Caution,3,Countryside concerns,16,7

In [9]:
import fiona
from shapely.geometry import Point

In [10]:
la["latfl"] = 1.*la.Lat
la["longfl"] = 1.*la.Long

In [11]:
la

,Ward,PostcodeSearch,Lat,Long,Category,CategoryOrder,CategoryGroup,CategoryGroupOrder,CategoryType,CategoryTypeOrder,WellbeingGroup,WellbeingGroupOrder,WellbeingType,WellbeingTypeOrder,TotalPopulation,latfl,longfl
0,Darwin,TN162HY,51.293412,0.073846,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,14,51.293412,0.073846
1,Darwin,TN162HX,51.293948,0.061807,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,29,51.293948,0.061807
2,Darwin,TN162HU,51.294801,0.073564,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,7,51.294801,0.073564
3,Darwin,TN162HW,51.295155,0.054044,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,42,51.295155,0.054044
4,Coulsdon East,CR35QU,51.295447,-0.108488,Affluent Achiever,1,Mature Money,3,"Settled suburbia, older people",11,Caution,3,Countryside concerns,16,70,51.295447,-0.108488
5,Coulsdon East,CR35QQ,51.295760,-0.107844,Affluent Achiever,1,Mature Money,3,"Settled suburbia, older people",11,Caution,3,Countryside concerns,16,39,51.295760,-0.107844
6,Coulsdon East,CR35QS,51.295966,-0.108883,Affluent Achiever,1,Mature Money,3,"Settled suburbia, older people",11,Caution,3,Countryside concerns,16,26,51.295966,-0.108883
7,Darwin,TN162JB,51.296103,0.083349,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,29,51.296103,0.083349
8,Darwin,TN162JE,51.296345,0.085884,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,44,51.296345,0.085884
9,Darwin,TN162JD,51.297715,0.085717,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Relishing retirement,19,10,51.297715,0.085717
10,Darwin,TN162JA,51.297740,0.076709,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,20,51.297740,0.076709
11,Coulsdon East,CR51DA,51.298248,-0.133935,Affluent Achiever,1,Mature Money,3,Better-off villagers,10,Healthy,4,Relishing retirement,19,21,51.298248,-0.133935
12,Coulsdon East,CR51BU,51.298330,-0.124435,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,At Risk,2,Anxious adversity,11,53,51.298330,-0.124435
13,Coulsdon East,CR51SX,51.298333,-0.108441,Affluent Achiever,1,Executive Wealth,2,Prosperous suburban families,8,Healthy,4,"Healthy, wealthy & wine",25,13,51.298333,-0.108441
14,Coulsdon East,CR51BX,51.298369,-0.122985,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,Caution,3,Rooted routines,14,52,51.298369,-0.122985
15,Coulsdon East,CR51BH,51.298412,-0.122266,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,At Risk,2,Anxious adversity,11,46,51.298412,-0.122266
16,Coulsdon East,CR51PX,51.298575,-0.113954,Comfortable Communities,3,Successful Suburbs,7,Comfortably-off families in modern housing,24,Caution,3,Countryside concerns,16,17,51.298575,-0.113954
17,Coulsdon East,CR51BT,51.298636,-0.120579,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,At Risk,2,Anxious adversity,11,81,51.298636,-0.120579
18,Coulsdon East,CR51BR,51.298641,-0.126488,Urban Adversity,5,Struggling Estates,16,"Poorer families, many children, terraced housing",52,Health Challenges,1,Hardship heartlands,3,31,51.298641,-0.126488
19,Darwin,TN162HR,51.298672,0.060656,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,28,51.298672,0.060656
20,Coulsdon East,CR51EE,51.298681,-0.117780,Financially Stretched,4,Poorer Pensioners,14,"Pensioners in social housing, semis and terraces",45,Health Challenges,1,Countryside complacency,5,23,51.298681,-0.117780
21,Coulsdon East,CR51EP,51.298771,-0.114993,Comfortable Communities,3,Countryside Communities,6,Owner occupiers in small towns and villages,23,Health Challenges,1,Elderly ailments,4,19,51.298771,-0.114993
22,Coulsdon East,CR51BW,51.298871,-0.121731,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,Caution,3,Rooted routines,14,8,51.298871,-0.121731
23,Coulsdon East,CR51EQ,51.298904,-0.114270,Affluent Achiever,1,Mature Money,3,"Settled suburbia, older people",11,Caution,3,Countryside concerns,16,14,51.298904,-0.114270
24,Darwin,TN162NS,51.298908,0.044600,Affluent Achiever,1,Executive Wealth,2,Well-off edge of towners,9,Healthy,4,Five-a-day greys,24,15,51.298908,0.044600
25,Coulsdon East,CR51DZ,51.299005,-0.123404,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,100,51.299005,-0.123404
26,Coulsdon East,CR51DW,51.299228,-0.124356,Urban Adversity,5,Difficult Circumstances,17,"Singles and young families, some receiving ben...",58,Health Challenges,1,Hardship heartlands,3,24,51.299228,-0.124356
27,Coulsdon East,CR51ER,51.299289,-0.114183,Comfortable Communities,3,Comfortable Seniors,9,"Older people, neat and tidy neighbourhoods",30,Health Challenges,1,Elderly ailments,4,31,51.299289,-0.114183
28,Coulsdon East,CR51DY,51.299325,-0.122014,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,107,51.299325,-0.122014
29,Coulsdon East,CR51BS,51.299338,-0.120048,Financially Stretched,4,Striving Families,13,Struggling young families in post-war terraces,42,Caution,3,Rooted routines,14,45,51.299338,-0.120048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178424,Turkey Street,EN88HT,51.682027,-0.047375,Comfortable Communities,3,Steady Neighbourhoods,8,"Owner occupied terraces, average income",28,Caution,3,Borderline behaviours,15,35,51.682027,-0.047375
178425,Turkey Street,EN88RG,51.682028,-0.043657,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,100,51.682028,-0.043657
178426,Turkey Street,EN88HS,51.682075,-0.045926,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,102,51.682075,-0.045926
178427,Turkey Street,EN88RY,51.682109,-0.042569,Urban Adversity,5,Difficult Circumstances,17,"Social rented flats, families and single parents",57,At Risk,2,Perilous futures,12,57,51.682109,-0.042569
178428,Turkey Street,EN88HP,51.682123,-0.045027,Urban Adversity,5,Difficult Circumstances,17,Deprived areas and high-rise flats,59,Health Challenges,1,Hardship heartlands,3,59,51.682123,-0.045027
178429,Turkey Street,EN88RA,51.682146,-0.037793,Comfortable Communities,3,Steady Neighbourhoods,8,"Owner occupied terraces, average income",28,Caution,3,Borderline behaviours,15,42,51.682146,-0.037793
178430,Turkey Street,EN88RB,51.682149,-0.040093,Comfortable Communities,3,Steady Neighbourhoods,8,"Owner occupied terraces, average income",28,Caution,3,Borderline behaviours,15,24,51.682149,-0.040093
178431,Turkey Street,EN88HR,51.682221,-0.045500,Urban Adversity,5,Difficult Circumstances,17,Deprived areas and high-rise flats,59,Health Challenges,1,Limited living,1,20,51.682221,-0.045500
178432,Chase,EN28BE,51.682237,-0.144648,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0,51.682237,-0.144648
178433,Chase,EN29HR,51.682454,-0.089177,Affluent Achiever,1,Mature Money,3,Better-off villagers,10,Healthy,4,Relishing retirement,19,5,51.682454,-0.089177
178434,Chase,EN29HW,51.682454,-0.089177,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,18,51.682454,-0.089177
178435,Chase,EN29DG,51.682690,-0.098194,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0,51.682690,-0.098194
178436,Chase,EN29ED,51.682853,-0.103265,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0,51.682853,-0.103265
178437,Chase,EN29DJ,51.683248,-0.100456,Affluent Achiever,1,Executive Wealth,2,Asset rich families,4,Healthy,4,Relishing retirement,19,6,51.683248,-0.100456
178438,Chase,EN29DX,51.683281,-0.104144,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0,51.683281,-0.104144
178439,Chase,EN29DN,51.683543,-0.103684,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,8,51.683543,-0.103684
178440,Chase,EN28AN,51.683609,-0.135304,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,7,51.683609,-0.135304
178441,Chase,EN29DZ,51.684038,-0.099251,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,21,51.684038,-0.099251
178442,Chase,EN29DR,51.684063,-0.104154,Affluent Achiever,1,Mature Money,3,Retired and empty nesters,12,Healthy,4,Sensible seniors,21,2,51.684063,-0.104154
178443,Chase,EN29DP,51.684083,-0.100899,Comfortable Communities,3,Countryside Communities,6,Larger families in rural areas,22,Healthy,4,Relishing retirement,19,3,51.684083,-0.100899
178444,Chase,EN28BA,51.684256,-0.111090,Affluent Achiever,1,Mature Money,3,Better-off villagers,10,Healthy,4,Relishing retirement,19,5,51.684256,-0.111090
178445,Chase,EN28AY,51.684257,-0.108949,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Relishing retirement,19,2,51.684257,-0.108949
178446,Chase,EN28AZ,51.684327,-0.109380,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Relishing retirement,19,7,51.684327,-0.109380
178447,Chase,EN29DS,51.684394,-0.105674,Comfortable Communities,3,Countryside Communities,6,Larger families in rural areas,22,Caution,3,Countryside concerns,16,14,51.684394,-0.105674
178448,Chase,EN29DW,51.684394,-0.105674,Affluent Achiever,1,Executive Wealth,2,Asset rich families,4,Healthy,4,Relishing retirement,19,2,51.684394,-0.105674
178449,Chase,EN29EE,51.684394,-0.105674,Not Private Households,6,Not Private Households,18,Business areas without resident population,62,Not Private Households,5,Business areas without resident population,28,0,51.684394,-0.105674
178450,Chase,EN65QT,51.684835,-0.158878,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,13,51.684835,-0.158878
178451,Chase,EN29DY,51.685128,-0.098815,Affluent Achiever,1,Executive Wealth,2,Wealthy countryside commuters,5,Healthy,4,Five-a-day greys,24,11,51.685128,-0.098815
178452,Chase,EN29AX,51.685433,-0.098238,Rising Prosperity,2,Career Climbers,5,Mixed metropolitan areas,20,Healthy,4,Gym & juices,22,28,51.685433,-0.098238
178453,Chase,EN29DU,51.688310,-0.105945,Affluent Achiever,1,Mature Money,3,Better-off villagers,10,Caution,3,Countryside concerns,16,7,51.688310,-0.105945

In [12]:
la["geom"] = la.apply(lambda row: Point(row["longfl"], row["latfl"]), axis=1)

In [13]:
lageo = gpd.GeoDataFrame(la, geometry="geom")

In [14]:
lageo.crs="WGS84"

In [15]:
pl.figure(figsize=(10,10))
lageo[:10000].plot(figsize=(10,10))

NameError: name 'pl' is not defined

In [17]:
import pylab as pl

In [18]:
%matplotlib inline

In [19]:
pd.Series({i: j for i,j in enumerate(set(la.Ward))}).shape()

TypeError: 'tuple' object is not callable

In [20]:
{i:j for i,j in enumerate(set(la.Ward))}

{0: 'Biggin Hill',
 1: 'Bow East',
 2: 'South Ruislip',
 3: 'Kenton West',
 4: 'Leyton',
 5: 'Queens Park',
 6: 'Lee Green',
 7: 'Croham',
 8: 'Carshalton Central',
 9: 'Hylands',
 10: 'Lancaster Gate',
 11: 'Fryent',
 12: 'Highgate',
 13: 'Purley',
 14: 'Erith',
 15: 'Cathedrals',
 16: 'Stroud Green',
 17: 'Peckham',
 18: 'Belvedere',
 19: 'Balham',
 20: 'Kelsey and Eden Park',
 21: 'Shirley',
 22: 'Rayners Lane',
 23: 'Lesnes Abbey',
 24: 'Heston Central',
 25: 'Norbiton',
 26: 'Hampton Wick',
 27: 'Whitechapel',
 28: 'Farringdon Without',
 29: 'East Finchley',
 30: "St George's",
 31: 'Bruce Grove',
 32: 'Poplar',
 33: 'Tokyngton',
 34: 'Shaftesbury',
 35: "St Mark's",
 36: 'Rushey Green',
 37: 'Whitefoot',
 38: 'Roehampton and Putney Heath',
 39: 'Raynes Park',
 40: 'Sydenham',
 41: 'East Ham Central',
 42: 'Fullwell',
 43: 'Highbury West',
 44: 'Falconwood and Welling',
 45: 'Harrow on the Hill',
 46: 'Thurlow Park',
 47: 'Chase',
 48: 'Chessington North and Hook',
 49: 'Woolwich Riverside',
 50: 'Hillrise',
 51: 'Enfield Lock',
 52: 'Bedfont',
 53: 'Church End',
 54: 'Marylebone High Street',
 55: "Figge's Marsh",
 56: 'Hayes and Coney Hall',
 57: 'Nunhead',
 58: "St Leonard's",
 59: 'Fieldway',
 60: 'Furzedown',
 61: 'Bayswater',
 62: 'Eltham North',
 63: 'Tulse Hill',
 64: 'Billingsgate',
 65: 'Highlands',
 66: 'Greenford Broadway',
 67: 'Northumberland Park',
 68: 'Heaton',
 69: 'Norland',
 70: 'Telegraph Hill',
 71: 'Osterley and Spring Grove',
 72: 'Kentish Town',
 73: 'Boleyn',
 74: 'Clerkenwell',
 75: 'Golders Green',
 76: 'Nonsuch',
 77: 'Havering Park',
 78: 'Harefield',
 79: 'Beverley',
 80: 'Grove Green',
 81: 'High Street',
 82: 'Northumberland Heath',
 83: 'Thornton',
 84: 'Munster',
 85: 'Abbey',
 86: 'Notting Dale',
 87: 'New Cross',
 88: 'Hatch End',
 89: 'Lower Edmonton',
 90: 'Camden Town with Primrose Hill',
 91: 'Northcote',
 92: 'Forest Gate North',
 93: 'Coulsdon West',
 94: 'Golborne',
 95: 'North End',
 96: 'Monkhams',
 97: 'Longlands',
 98: 'Feltham North',
 99: 'Tachbrook',
 100: "St Michael's",
 101: 'Tudor',
 102: 'Surbiton Hill',
 103: 'Cranbrook',
 104: 'Wood Street',
 105: 'North Greenford',
 106: 'Herne Hill',
 107: 'The Lane',
 108: 'Avonmore and Brook Green',
 109: 'Hackney Downs',
 110: 'West Hendon',
 111: 'Mottingham and Chislehurst North',
 112: 'Lime Street',
 113: 'Bread Street',
 114: "King's Cross",
 115: 'Sutton South',
 116: 'East Ham North',
 117: 'Palace Riverside',
 118: 'Cantelowes',
 119: 'Pinner',
 120: 'Pollards Hill',
 121: 'Bloomsbury',
 122: 'Hampstead Town',
 123: 'Chislehurst',
 124: 'Graveney',
 125: 'Hounslow West',
 126: 'De Beauvoir',
 127: 'Holland',
 128: 'Muswell Hill',
 129: 'Stanmore Park',
 130: 'Bensham Manor',
 131: 'Spitalfields & Banglatown',
 132: 'Northolt Mandeville',
 133: "Prince's",
 134: 'Northwood Hills',
 135: 'Sutton Central',
 136: 'Roxbourne',
 137: 'Fortis Green',
 138: 'Camberwell Green',
 139: 'Churchill',
 140: 'Longbridge',
 141: 'Roding',
 142: 'Royal Docks',
 143: 'Cray Valley East',
 144: 'Dalston',
 145: 'Thornton Heath',
 146: 'Stonebridge',
 147: 'Stepney Green',
 148: 'Southfields',
 149: 'Harringay',
 150: 'Queenhithe',
 151: 'Grove Park',
 152: 'Thamesmead East',
 153: 'Walpole',
 154: 'Hainault',
 155: 'Warwick',
 156: 'Mildmay',
 157: 'Trinity',
 158: 'Addison',
 159: 'Garden Suburb',
 160: 'Stratford and New Town',
 161: 'Enfield Highway',
 162: 'Marlborough',
 163: 'Chelsea Riverside',
 164: 'Downham',
 165: 'Yiewsley',
 166: 'Stockwell',
 167: 'Hoe Street',
 168: 'West Putney',
 169: 'South Twickenham',
 170: 'Forest Hill',
 171: 'Gipsy Hill',
 172: 'Bassishaw',
 173: 'Valentines',
 174: 'Pembridge',
 175: 'Hendon',
 176: "St Peter's",
 177: 'Frognal and Fitzjohns',
 178: 'Hounslow Heath',
 179: 'Tower',
 180: 'Leytonstone',
 181: 'Belsize',
 182: 'West Harrow',
 183: 'East Walworth',
 184: 'Winchmore Hill',
 185: 'Ravenscourt Park',
 186: 'South Camberwell',
 187: 'Coombe Hill',
 188: 'Candlewick',
 189: 'Hoxton East & Shoreditch',
 190: 'Stanley',
 191: 'Lower Morden',
 192: "Queen's Gate",
 193: 'Noel Park',
 194: 'Earlsfield',
 195: 'Hyde Park',
 196: 'Chaucer',
 197: "Queen's Park",
 198: 'Queensbury',
 199: 'Childs Hill',
 200: 'Woolwich Common',
 201: 'Ashburton',
 202: 'Wormholt and White City',
 203: "St Dunstan's",
 204: 'Junction',
 205: 'East Dulwich',
 206: 'Newbury',
 207: 'Greenford Green',
 208: 'Snaresbrook',
 209: 'Dormers Wells',
 210: 'Kew',
 211: 'Bunhill',
 212: 'Holloway',
 213: 'Town',
 214: 'Colliers Wood',
 215: 'Perry Vale',
 216: 'Custom House',
 217: 'Grove',
 218: 'Dundonald',
 219: 'Tooting',
 220: 'Fortune Green',
 221: 'Tollington',
 222: 'Clapham Common',
 223: 'Brompton & Hans Town',
 224: "Regent's Park",
 225: 'Hoxton West',
 226: 'Brampton',
 227: 'Finsbury Park',
 228: 'Harrow Weald',
 229: 'Charlton',
 230: 'North Richmond',
 231: 'Bush Hill Park',
 232: 'Perivale',
 233: 'Faraday',
 234: 'Gascoigne',
 235: 'Oakleigh',
 236: 'Headstone North',
 237: 'Townfield',
 238: 'Ealing Broadway',
 239: 'Wall End',
 240: 'Hale End and Highams Park',
 241: 'Clock House',
 242: 'Highbury East',
 243: 'Parsloes',
 244: 'Hacton',
 245: 'Colville',
 246: 'St Helier',
 247: 'Sutton West',
 248: 'West End',
 249: "Bishop's",
 250: 'Chingford Green',
 251: 'Uxbridge North',
 252: 'Hatch Lane',
 253: 'Lewisham Central',
 254: 'Plaistow and Sundridge',
 255: 'Streatham Wells',
 256: 'West Ruislip',
 257: 'Seven Sisters',
 258: 'Thames',
 259: 'Valence',
 260: 'Upper Edmonton',
 261: 'East Acton',
 262: 'The Wrythe',
 263: 'Seven Kings',
 264: 'Bromley North',
 265: 'Swiss Cottage',
 266: 'Canonbury',
 267: "St. Helen's",
 268: 'Redcliffe',
 269: 'Hillside',
 270: 'Crofton Park',
 271: 'Kilburn',
 272: 'Markhouse',
 273: 'Oval',
 274: 'Dowgate',
 275: 'Limehouse',
 276: 'Catford South',
 277: 'Haggerston',
 278: 'Cray Meadows',
 279: 'Grange',
 280: 'Valley',
 281: 'Thamesmead Moorings',
 282: 'Chiswick Riverside',
 283: 'Coldharbour',
 284: 'Clayhall',
 285: 'Hale',
 286: 'Shacklewell',
 287: 'Ravensbury',
 288: 'Haverstock',
 289: 'Weavers',
 290: 'Lansbury',
 291: 'Goresbrook',
 292: 'Heston West',
 293: 'Harold Wood',
 294: 'Chessington South',
 295: 'Canary Wharf',
 296: 'Askew',
 297: 'Heath',
 298: 'Becontree',
 299: 'Pinkwell',
 300: 'Beddington North',
 301: 'Fairlop',
 302: 'Mayesbrook',
 303: 'Willesden Green',
 304: 'Pinner South',
 305: 'Bridge',
 306: 'Fulwell and Hampton Hill',
 307: 'Chelsfield and Pratts Bottom',
 308: 'East Ham South',
 309: 'Roxeth',
 310: 'Caledonian',
 311: 'Romford Town',
 312: 'Palmers Green',
 313: 'Brownswood',
 314: 'Bryanston and Dorset Square',
 315: 'Jubilee',
 316: 'Cordwainer',
 317: 'Plaistow South',
 318: 'Southbury',
 319: 'Campden',
 320: 'Hammersmith Broadway',
 321: 'Portsoken',
 322: 'Fulham Reach',
 323: 'Hanger Hill',
 324: 'West Drayton',
 325: 'Bow West',
 326: 'Greenhill',
 327: 'Mapesbury',
 328: 'Vintry',
 329: 'Barnes',
 330: 'Coldharbour and New Eltham',
 331: 'Bedford',
 332: 'Haselbury',
 333: 'South Bermondsey',
 334: 'Wembley Central',
 335: 'Northfield',
 336: 'Nightingale',
 337: 'Hounslow Central',
 338: 'River',
 339: 'Edgware',
 340: 'Larkhall',
 341: 'Sudbury',
 342: 'Southall Broadway',
 343: 'Charville',
 344: 'Crystal Palace',
 345: 'Abbey Road',
 346: 'Heathfield',
 347: 'West Green',
 348: 'Broad Green',
 349: 'Latchmere',
 350: 'Hobbayne',
 351: 'South Hornchurch',
 352: 'Bounds Green',
 353: 'Kenton East',
 354: 'Goodmayes',
 355: 'Brockley',
 356: 'Southgate Green',
 357: 'Hampton North',
 358: 'Stonecot',
 359: 'Lady Margaret',
 360: 'Woodside',
 361: 'Carshalton South and Clockhouse',
 362: 'Syon',
 363: "Squirrel's Heath",
 364: 'Northwick Park',
 365: 'Colindale',
 366: 'Island Gardens',
 367: 'Cray Valley West',
 368: 'Mile End',
 369: 'Brooklands',
 370: 'Woodberry Down',
 371: 'Whalebone',
 372: 'Queenstown',
 373: 'Shooters Hill',
 374: 'West Twickenham',
 375: 'Heston East',
 376: 'Chiswick Homefields',
 377: "St Mary's Park",
 378: 'Canbury',
 379: 'Barnsbury',
 380: 'Stoke Newington',
 381: 'Wealdstone',
 382: 'Beckton',
 383: 'Whitton',
 384: 'East Wickham',
 385: 'Gospel Oak',
 386: 'Norwood Green',
 387: 'Hackney Central',
 388: 'Ponders End',
 389: 'Tottenham Green',
 390: 'Lea Bridge',
 391: 'Rainham and Wennington',
 392: 'Middle Park and Sutcliffe',
 393: 'Emerson Park',
 394: 'Sidcup',
 395: 'Forest',
 396: 'New Addington',
 397: 'Riverside',
 398: 'Cazenove',
 399: 'Chadwell Heath',
 400: 'Hornsey',
 401: 'Coulsdon East',
 402: 'Old Malden',
 403: 'Loxford',
 404: 'Cranford',
 405: 'College Park and Old Oak',
 406: 'Brondesbury Park',
 407: 'Brentford',
 408: 'Maida Vale',
 409: 'Elthorne',
 410: 'Cripplegate',
 411: 'Mayfield',
 412: 'Royal Hospital',
 413: 'Alexandra',
 414: 'Cornhill',
 415: 'Clementswood',
 416: 'Blackheath Westcombe',
 417: 'College',
 418: 'Cleveland',
 419: 'St James',
 420: 'East Barnet',
 421: 'Coppetts',
 422: "St Andrew's",
 423: 'Mortlake and Barnes Common',
 424: "Knight's Hill",
 425: 'Higham Hill',
 426: 'Crayford',
 427: 'Danson Park',
 428: 'Kenton',
 429: 'Farnborough and Crofton',
 430: 'Gooshays',
 431: 'Blackfen and Lamorbey',
 432: 'Alibon',
 433: 'Teddington',
 434: 'West Ham',
 435: 'Fulham Broadway',
 436: 'Brixton Hill',
 437: 'Edmonton Green',
 438: 'Clissold',
 439: 'Sands End',
 440: 'Bethnal Green',
 441: 'Upper Norwood',
 442: 'Kenley',
 443: 'Beddington South',
 444: 'Burnt Oak',
 445: 'Petts Wood and Knoll',
 446: 'Cockfosters',
 447: "St Katharine's & Wapping",
 448: 'Thamesfield',
 449: 'St Margarets and North Twickenham',
 450: 'Harrow Road',
 451: 'Vassall',
 452: 'Hampton',
 453: 'Bickley',
 454: 'Evelyn',
 455: 'Chapel End',
 456: 'Isleworth',
 457: 'Barnhill',
 458: 'Hillingdon East',
 459: 'Mawneys',
 460: 'Brunswick Park',
 461: 'Lavender Fields',
 462: 'London Fields',
 463: 'Headstone South',
 464: 'Ickenham',
 465: 'Tottenham Hale',
 466: 'Forest Gate South',
 467: 'Berrylands',
 468: 'Turkey Street',
 469: 'Selhurst',
 470: 'Walbrook',
 471: 'Heathrow Villages',
 472: 'Wandle Valley',
 473: 'Cannon Hill',
 474: 'Chadwell',
 475: 'Victoria',
 476: 'Dudden Hill',
 477: 'Twickenham Riverside',
 478: 'Green Street West',
 479: 'Cavendish',
 480: 'Cranham',
 481: 'Cricket Green',
 482: 'Coleman Street',
 483: "King's Park",
 484: 'Christchurch',
 485: 'Castle Baynard',
 486: 'Barkingside',
 487: 'Blackwall & Cubitt Town',
 488: 'Hackney Wick',
 489: 'Bellingham',
 490: 'Peckham Rye',
 491: 'Broad Street',
 492: 'Surrey Docks',
 493: 'Streatham South',
 494: 'Welsh Harp',
 495: 'Belmont',
 496: 'Blendon and Penhill',
 497: 'Greenwich West',
 498: 'Bishopsgate',
 499: 'Waddon',
 500: 'South Norwood',
 501: 'Copers Cope',
 502: 'Botwell',
 503: 'Orpington',
 504: 'Elm Park',
 505: 'Woodhouse',
 506: 'Plumstead',
 507: 'Wandsworth Common',
 508: 'Hounslow South',
 509: 'Plaistow North',
 510: 'Hanworth',
 511: 'Ladywell',
 512: 'Aldborough',
 513: 'East Putney',
 514: 'Longthornton',
 515: 'Endlebury',
 516: 'Bromley Common and Keston',
 517: 'South Richmond',
 518: 'Westbourne',
 519: 'Addiscombe',
 520: 'Kensal Green',
 521: "St Mary's",
 522: 'East Sheen',
 523: 'Harlesden',
 524: 'Colyers',
 525: 'William Morris',
 526: 'Rotherhithe',
 527: 'South Acton',
 528: 'Canons',
 529: 'Wimbledon Park',
 530: 'Eastbrook',
 531: 'Livesey',
 532: 'Newington',
 533: 'Ham, Petersham and Richmond Riverside',
 534: 'Dollis Hill',
 535: 'Turnham Green',
 536: 'West Hill',
 537: 'Farringdon Within',
 538: 'Cheap',
 539: 'Crouch End',
 540: 'Cheam',
 541: 'Penge and Cator',
 542: 'Homerton',
 543: 'Cathall',
 544: 'Dalgarno',
 545: 'Fairfield',
 546: 'Larkswood',
 547: 'Yeading',
 548: 'St Pancras and Somers Town',
 549: 'Southall Green',
 550: 'Northwood',
 551: 'Acton Central',
 552: 'Aldgate',
 553: 'Brunel',
 554: 'Bromley Town',
 555: 'Vincent Square',
 556: 'Blackheath',
 557: 'Abbey Wood',
 558: 'Eltham South',
 559: 'Peninsula',
 560: 'West Finchley',
 561: 'Green Street East',
 562: 'Bowes',
 563: 'Norbury',
 564: "Earl's Court",
 565: 'Courtfield',
 566: 'Coombe Vale',
 567: 'Wanstead',
 568: 'Clapham Town',
 569: 'Wallington North',
 570: 'West Barnes',
 571: 'Southgate',
 572: 'Canning Town South',
 573: 'Southfield',
 574: 'Bromley South',
 575: 'Barnehurst',
 576: "Shepherd's Bush Green",
 577: 'Glyndon',
 578: 'Preston',
 579: 'Aldersgate',
 580: 'West Thornton',
 581: 'Sutton North',
 582: 'Finchley Church End',
 583: 'Tolworth and Hook Rise',
 584: 'Selsdon and Ballards',
 585: 'High Barnet',
 586: 'White Hart Lane',
 587: 'Church Street',
 588: 'Eastbury',
 589: 'West Hampstead',
 590: 'Totteridge',
 591: 'Cann Hall',
 592: 'Darwin',
 593: "St James's",
 594: 'Springfield',
 595: 'Sanderstead',
 596: 'Manor',
 597: 'Streatham Hill',
 598: 'Worcester Park',
 599: 'Knightsbridge and Belgravia',
 600: 'Mill Hill',
 601: 'Alperton',
 602: 'Manor Park',
 603: 'Little Ilford',
 604: 'Ferndale',
 605: 'Stamford Hill West',
 606: 'Upminster',
 607: 'Uxbridge South',
 608: 'Eastcote and East Ruislip',
 609: 'Holborn and Covent Garden',
 610: 'Underhill',
 611: 'Eltham West',
 612: 'Langbourn',
 613: 'Wallington South',
 614: 'Pettits',
 615: 'Canning Town North',
 616: 'Ealing Common',
 617: 'Little Venice',
 618: 'Parsons Green and Walham',
 619: 'West Wickham',
 620: 'Abingdon',
 621: 'Hanworth Park',
 622: 'Merton Park',
 623: 'Kidbrooke with Hornfair',
 624: 'Shortlands',
 625: 'Northolt West End',
 626: 'Feltham West',
 627: "St Ann's",
 628: 'Village',
 629: 'Shadwell'}

In [21]:
gr = la.groupby(['Ward', 'CategoryGroup']).agg({'CategoryGroup': 'count'})

In [22]:
gr = gr.unstack()

In [23]:
gr.columns = gr.columns.get_level_values(1) #[' '.join(col).strip() for col in gr.columns.values]

In [24]:
gr.index.name

'Ward'

In [25]:
gr = gr.reset_index()
#gr.reindex_axis(gr.index[0], axis=0)

In [26]:
import numpy as np

In [27]:
gr.to_csv('./ward-acorntypegroup-aggregation.csv')

In [29]:
income = pd.read_csv('../londonincome.csv')

In [30]:
income

,Code,Ward name,LAD code,Borough,2001/02,2002/03,2003/04,2004/05,2005/06,2006/07,2007/08,2008/09,2009/10,2010/11,2011/12,2012/13
0,E09000001,City of London,E09000001,City of London,65120,66410,69800,74510,76200,81300,83050,89340,89680,93380,97030,99390
1,E05000026,Abbey,E09000002,Barking and Dagenham,25540,25920,27150,28920,29550,31530,32230,34710,34890,36380,37870,38870
2,E05000027,Alibon,E09000002,Barking and Dagenham,23980,24390,25610,27350,28000,29940,30660,33080,33320,34810,36290,37290
3,E05000028,Becontree,E09000002,Barking and Dagenham,25250,25580,26750,28450,29030,30920,31560,33950,34090,35510,36930,37860
4,E05000029,Chadwell Heath,E09000002,Barking and Dagenham,25950,26290,27490,29240,29830,31770,32430,34870,35010,36470,37910,38860
5,E05000030,Eastbrook,E09000002,Barking and Dagenham,29330,29640,30920,32800,33380,35470,36100,38730,38790,40310,41820,42780
6,E05000031,Eastbury,E09000002,Barking and Dagenham,24970,25300,26470,28170,28760,30660,31310,33710,33870,35320,36760,37720
7,E05000032,Gascoigne,E09000002,Barking and Dagenham,22700,22980,24020,25550,26070,27780,28370,30530,30680,31980,33270,34140
8,E05000033,Goresbrook,E09000002,Barking and Dagenham,24290,24720,25980,27760,28440,30440,31200,33690,33960,35510,37060,38130
9,E05000034,Heath,E09000002,Barking and Dagenham,23660,24010,25160,26810,27400,29250,29900,32210,32380,33780,35160,36080
10,E05000035,Longbridge,E09000002,Barking and Dagenham,34020,34150,35380,37280,37680,39790,40260,42950,42780,44240,45680,46520
11,E05000036,Mayesbrook,E09000002,Barking and Dagenham,24010,24340,25460,27090,27660,29490,30120,32420,32580,33970,35360,36280
12,E05000037,Parsloes,E09000002,Barking and Dagenham,23950,24310,25470,27140,27740,29610,30280,32630,32820,34250,35680,36640
13,E05000038,River,E09000002,Barking and Dagenham,25320,25690,26900,28640,29250,31200,31870,34320,34490,35950,37420,38390
14,E05000039,Thames,E09000002,Barking and Dagenham,24840,25180,26340,28030,28610,30500,31140,33510,33650,35070,36470,37400
15,E05000040,Valence,E09000002,Barking and Dagenham,24340,24770,26020,27790,28470,30460,31210,33700,33950,35490,37030,38080
16,E05000041,Village,E09000002,Barking and Dagenham,24470,24780,25900,27540,28100,29940,30570,32890,33030,34430,35810,36740
17,E05000042,Whalebone,E09000002,Barking and Dagenham,29910,30150,31370,33190,33690,35710,36270,38820,38800,40230,41660,42530
18,E05000043,Brunswick Park,E09000003,Barnet,37840,38170,39730,42030,42650,45180,45840,49020,48940,50690,52420,53440
19,E05000044,Burnt Oak,E09000003,Barnet,26640,26920,28080,29790,30320,32220,32810,35220,35290,36700,38100,39000
20,E05000045,Childs Hill,E09000003,Barnet,38500,38650,40030,42170,42600,44940,45430,48410,48170,49750,51310,52190
21,E05000046,Colindale,E09000003,Barnet,27820,28060,29210,30940,31430,33350,33900,36330,36350,37740,39120,39990
22,E05000047,Coppetts,E09000003,Barnet,36930,37160,38580,40720,41220,43570,44110,47070,46890,48470,50020,50910
23,E05000048,East Barnet,E09000003,Barnet,36690,37150,38800,41190,41930,44550,45350,48630,48670,50550,52390,53550
24,E05000049,East Finchley,E09000003,Barnet,38050,38530,40240,42720,43480,46190,47010,50400,50440,52380,54290,55480
25,E05000050,Edgware,E09000003,Barnet,38750,38840,40160,42220,42570,44830,45230,48100,47750,49210,50630,51380
26,E05000051,Finchley Church End,E09000003,Barnet,43760,44180,45990,48660,49360,52270,53000,56640,56490,58460,60390,61510
27,E05000052,Garden Suburb,E09000003,Barnet,51250,51980,54350,57740,58790,62480,63580,68160,68200,70790,73350,74940
28,E05000053,Golders Green,E09000003,Barnet,39550,39850,41410,43750,44320,46870,47490,50700,50530,52260,53960,54940
29,E05000054,Hale,E09000003,Barnet,36330,36640,38140,40360,40970,43420,44090,47180,47140,48880,50600,51650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,E05000620,Queenstown,E09000032,Wandsworth,37120,37560,39200,41590,42310,44940,45710,49000,49020,50880,52710,53840
596,E05000621,Roehampton,E09000032,Wandsworth,27890,28180,29390,31170,31730,33730,34350,36880,36970,38450,39920,40880
597,E05000622,St Mary's Park,E09000032,Wandsworth,41840,42450,44410,47230,48140,51210,52170,55990,56080,58260,60420,61760
598,E05000623,Shaftesbury,E09000032,Wandsworth,48120,48890,51210,54490,55560,59110,60210,64600,64670,67150,69590,71090
599,E05000624,Southfields,E09000032,Wandsworth,45740,46410,48550,51610,52580,55910,56930,61080,61150,63520,65860,67330
600,E05000625,Thamesfield,E09000032,Wandsworth,56130,56830,59310,62880,63880,67710,68710,73460,73270,75820,78300,79730
601,E05000626,Tooting,E09000032,Wandsworth,35670,35830,37140,39150,39590,41800,42280,45080,44870,46350,47810,48630
602,E05000627,Wandsworth Common,E09000032,Wandsworth,47420,48340,50790,54230,55480,59240,60560,65210,65520,68280,71020,72820
603,E05000628,West Hill,E09000032,Wandsworth,36450,37030,38810,41340,42210,45000,45940,49410,49600,51650,53680,55010
604,E05000629,West Putney,E09000032,Wandsworth,40460,41020,42890,45570,46430,49370,50280,53950,54020,56120,58190,59490
605,E05000630,Abbey Road,E09000033,Westminster,62940,63580,66250,70170,71270,75590,76790,82220,82190,85250,88290,90170
606,E05000631,Bayswater,E09000033,Westminster,57740,58600,61330,65240,66520,70790,72140,77460,77610,80670,83690,85610
607,E05000632,Bryanston and Dorset Square,E09000033,Westminster,61760,62520,65260,69220,70370,74660,75840,81150,81040,83950,86790,88470
608,E05000633,Churchill,E09000033,Westminster,39330,40380,42770,46040,47500,51130,52700,57200,57930,60830,63740,65830
609,E05000634,Church Street,E09000033,Westminster,33830,33770,34820,36530,36780,38700,39020,41490,41200,42470,43710,44380
610,E05000635,Harrow Road,E09000033,Westminster,40830,41210,42910,45430,46130,48910,49660,53140,53080,55000,56890,58030
611,E05000636,Hyde Park,E09000033,Westminster,57470,57870,60110,63470,64270,67950,68810,73440,73180,75670,78110,79530
612,E05000637,Knightsbridge and Belgravia,E09000033,Westminster,82810,88070,96340,106780,113100,124660,131210,145120,149450,159340,169240,176950
613,E05000638,Lancaster Gate,E09000033,Westminster,58520,59190,61760,65490,66580,70660,71820,76920,76890,79750,82560,84280
614,E05000639,Little Venice,E09000033,Westminster,61720,62020,64290,67730,68420,72160,72900,77620,77150,79580,81950,83230
615,E05000640,Maida Vale,E09000033,Westminster,55580,56030,58260,61580,62390,65990,66850,71350,71090,73490,75830,77170
616,E05000641,Marylebone High Street,E09000033,Westminster,65760,67240,70870,75880,77830,83280,85290,92000,92570,96600,100590,103240
617,E05000642,Queen's Park,E09000033,Westminster,35490,35990,37660,40090,40930,43630,44550,47940,48150,50170,52190,53520
618,E05000643,Regent's Park,E09000033,Westminster,57710,58070,60280,63600,64340,67950,68740,73270,72900,75260,77560,78810
619,E05000644,St James's,E09000033,Westminster,58180,59470,62680,67100,68820,73630,75390,81270,81720,85200,88610,90820
620,E05000645,Tachbrook,E09000033,Westminster,55130,55820,58300,61900,63010,66950,68130,73050,73120,75920,78690,80420
621,E05000646,Vincent Square,E09000033,Westminster,51800,52710,55320,59000,60320,64370,65770,70780,71090,74050,76980,78880
622,E05000647,Warwick,E09000033,Westminster,59700,60510,63240,67150,68340,72560,73770,78980,78910,81770,84550,86200
623,E05000648,Westbourne,E09000033,Westminster,38700,38920,40410,42660,43210,45700,46320,49470,49330,51050,52740,53730
624,E05000649,West End,E09000033,Westminster,61800,63060,66350,70930,72670,77690,79500,85690,86170,89870,93530,95940

In [121]:
gr = gr.merge(income.drop(income.columns[4:-1], axis=1).rename(columns={'Ward name':'Ward'}), on='Ward')

In [32]:
gr.to_csv('./merged_acorn_income_by-ward.csv')

In [33]:
ordest = pd.read_csv('../Origin-desination matrix by station-zone-time of day 2015 csv.csv')

In [34]:
ordest = ordest.drop(ordest.columns[12:], axis =1).rename(columns={"Unnamed: 1": "FromName", "Unnamed: 3": "ToName"})

In [35]:
ordest

,From,FromName,To,ToName,Early,AM peak,Midday,PM Peak,Evening,Late,Evening Late Total,Zone
0,669,Oxford Circus,741,Victoria,28,158,2139,2978,1596,649,2245,1
1,513,Bank / Monument,728,Tottenham Court Road,94,807,1220,792,1054,297,1351,1
2,625,King's Cross St. Pancras,741,Victoria,119,1965,1887,1251,1022,244,1266,1
3,574,Euston,741,Victoria,152,1359,1691,2157,956,286,1242,1
4,674,Piccadilly Circus,670,Paddington,0,36,495,872,623,458,1081,1
5,542,Embankment,741,Victoria,124,377,742,1124,573,489,1062,1
6,625,King's Cross St. Pancras,670,Paddington,208,2458,2830,1790,846,178,1024,1
7,674,Piccadilly Circus,741,Victoria,0,0,441,673,424,568,992,1
8,751,Wembley Central,674,Piccadilly Circus,0,72,0,12,161,150,311,4
9,590,Green Park,741,Victoria,10,87,904,1368,606,311,917,1
10,669,Oxford Circus,670,Paddington,8,56,773,1146,614,218,832,1
11,574,Euston,669,Oxford Circus,64,1400,2641,721,716,0,716,1
12,631,Leicester Square,741,Victoria,0,0,348,480,323,382,705,1
13,745,Warren Street,741,Victoria,33,107,721,1456,508,142,650,1
14,708,South Kensington,741,Victoria,0,125,765,1043,431,212,643,1
15,577,Farringdon,670,Paddington,28,198,1089,1698,370,208,578,1
16,728,Tottenham Court Road,718,Charing Cross,3,21,299,439,300,274,574,1
17,669,Oxford Circus,718,Charing Cross,0,22,394,759,409,135,544,1
18,645,Moorgate,511,Baker Street,17,108,590,754,413,129,542,1
19,741,Victoria,669,Oxford Circus,197,2590,3159,1231,387,143,530,1
20,763,Whitechapel,741,Victoria,108,279,282,614,490,0,490,2
21,634,Liverpool Street,670,Paddington,127,747,912,1115,373,111,484,1
22,702,Sloane Square,741,Victoria,16,95,600,523,323,156,479,1
23,626,Knightsbridge,674,Piccadilly Circus,5,54,762,606,341,137,478,1
24,669,Oxford Circus,681,Queensway,0,0,79,73,227,230,457,1
25,634,Liverpool Street,669,Oxford Circus,102,1721,2436,1624,397,55,452,1
26,634,Liverpool Street,741,Victoria,98,556,751,633,323,126,449,1
27,593,Hammersmith (Dis),741,Victoria,53,249,432,628,222,227,449,2
28,575,Euston Square,670,Paddington,36,288,663,957,378,65,443,1
29,631,Leicester Square,728,Tottenham Court Road,0,0,444,348,235,198,433,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5619,779,Hatton Cross,631,Leicester Square,0,17,48,15,0,0,0,"5,6"
5620,779,Hatton Cross,637,Maida Vale,0,10,0,0,0,0,0,"5,6"
5621,779,Hatton Cross,641,Marylebone,0,0,0,1,0,0,0,"5,6"
5622,779,Hatton Cross,669,Oxford Circus,7,7,10,3,0,0,0,"5,6"
5623,779,Hatton Cross,670,Paddington,17,24,11,0,0,0,0,"5,6"
5624,779,Hatton Cross,674,Piccadilly Circus,7,28,57,16,0,0,0,"5,6"
5625,779,Hatton Cross,685,Regent's Park,5,0,0,0,0,0,0,"5,6"
5626,779,Hatton Cross,690,Royal Oak,0,0,5,0,0,0,0,"5,6"
5627,779,Hatton Cross,695,St. James's Park,15,39,21,0,0,0,0,"5,6"
5628,779,Hatton Cross,696,St. John's Wood,0,18,0,0,0,0,0,"5,6"
5629,779,Hatton Cross,724,Temple,0,0,1,4,0,0,0,"5,6"
5630,779,Hatton Cross,728,Tottenham Court Road,0,5,0,0,0,0,0,"5,6"
5631,779,Hatton Cross,741,Victoria,0,22,15,41,0,0,0,"5,6"
5632,779,Hatton Cross,746,Warwick Avenue,0,0,0,0,0,0,0,"5,6"
5633,779,Hatton Cross,754,Westbourne Park,0,0,0,1,0,0,0,"5,6"
5634,646,Moor Park,511,Baker Street,1,21,20,52,0,0,0,"6,7"
5635,646,Moor Park,524,Bond Street,0,9,0,0,0,0,0,"6,7"
5636,646,Moor Park,718,Charing Cross,0,1,9,45,0,0,0,"6,7"
5637,646,Moor Park,542,Embankment,0,0,0,0,0,0,0,"6,7"
5638,646,Moor Park,588,Great Portland Street,3,23,0,0,0,0,0,"6,7"
5639,646,Moor Park,590,Green Park,11,35,13,4,0,0,0,"6,7"
5640,646,Moor Park,614,Hyde Park Corner,0,27,0,0,0,0,0,"6,7"
5641,646,Moor Park,631,Leicester Square,0,14,0,20,0,0,0,"6,7"
5642,646,Moor Park,669,Oxford Circus,0,2,0,59,0,0,0,"6,7"
5643,646,Moor Park,674,Piccadilly Circus,1,5,30,0,0,0,0,"6,7"
5644,646,Moor Park,685,Regent's Park,0,3,2,0,0,0,0,"6,7"
5645,646,Moor Park,724,Temple,0,0,0,0,0,0,0,"6,7"
5646,646,Moor Park,728,Tottenham Court Road,0,0,0,10,0,0,0,"6,7"
5647,646,Moor Park,741,Victoria,1,1,0,0,0,0,0,"6,7"
5648,646,Moor Park,761,Westminster,9,45,0,0,0,0,0,"6,7"

In [36]:
tubelocs = pd.read_csv('../tubelocations.csv')

In [37]:
tubelocs

,id,latitude,longitude,name,display_name,zone,total_lines,rail
0,1,51.5028,-0.2801,Acton Town,Acton<br />Town,3.0,2,0
1,2,51.5143,-0.0755,Aldgate,NaN,1.0,2,0
2,3,51.5154,-0.0726,Aldgate East,Aldgate<br />East,1.0,2,0
3,4,51.5107,-0.0130,All Saints,All<br />Saints,2.0,1,0
4,5,51.5407,-0.2997,Alperton,NaN,4.0,1,0
5,7,51.5322,-0.1058,Angel,NaN,1.0,1,0
6,8,51.5653,-0.1353,Archway,NaN,2.5,1,0
7,9,51.6164,-0.1331,Arnos Grove,Arnos<br />Grove,4.0,1,0
8,10,51.5586,-0.1059,Arsenal,NaN,2.0,1,0
9,11,51.5226,-0.1571,Baker Street,Baker<br />Street,1.0,5,0
10,12,51.4431,-0.1525,Balham,NaN,3.0,1,1
11,13,51.5133,-0.0886,Bank,NaN,1.0,4,0
12,14,51.5204,-0.0979,Barbican,NaN,1.0,3,0
13,15,51.5396,0.0810,Barking,NaN,4.0,2,1
14,16,51.5856,0.0887,Barkingside,NaN,5.0,1,0
15,17,51.4905,-0.2139,Barons Court,Barons<br />Court,2.0,2,0
16,18,51.5121,-0.1879,Bayswater,NaN,1.0,2,0
17,19,51.5148,0.0613,Beckton,NaN,3.0,1,0
18,20,51.5087,0.0550,Beckton Park,Beckton<br />Park,3.0,1,0
19,21,51.5403,0.1270,Becontree,NaN,5.0,1,0
20,22,51.5504,-0.1642,Belsize Park,Belsize<br />Park,2.0,1,0
21,24,51.5270,-0.0549,Bethnal Green,Bethnal<br />Green,2.0,1,0
22,25,51.5120,-0.1031,Blackfriars,NaN,1.0,2,0
23,26,51.5867,-0.0417,Blackhorse Road,Blackhorse<br />Road,3.0,1,1
24,27,51.5079,-0.0066,Blackwall,NaN,2.0,1,0
25,28,51.5142,-0.1494,Bond Street,Bond<br />Street,1.0,2,0
26,29,51.5011,-0.0943,Borough,NaN,1.0,1,0
27,30,51.4956,-0.3250,Boston Manor,Boston<br />Manor,4.0,1,0
28,31,51.6071,-0.1243,Bounds Green,Bounds<br />Green,3.5,1,0
29,32,51.5273,-0.0208,Bow Church,Bow<br />Church,2.0,1,0
...,...,...,...,...,...,...,...,...
276,214,51.6404,-0.4733,Rickmansworth,NaN,7.0,1,0
277,62,51.6470,-0.4412,Croxley,NaN,7.0,1,0
278,280,51.6573,-0.4177,Watford,NaN,8.0,1,0
279,221,51.5606,-0.4103,Ruislip Gardens,Ruislip<br />Gardens,5.0,1,0
280,121,51.6503,-0.1943,High Barnet,High<br />Barnet,5.0,1,0
281,261,51.6302,-0.1791,Totteridge & Whetstone,Totteridge<br />& Whetstone,4.0,1,0
282,57,51.6517,-0.1496,Cockfosters,NaN,5.0,1,0
283,187,51.6476,-0.1318,Oakwood,NaN,5.0,1,0
284,232,51.6322,-0.1280,Southgate,NaN,4.0,1,0
285,88,51.6937,0.1139,Epping,NaN,6.0,1,0
286,256,51.6717,0.1033,Theydon Bois,Theydon<br />Bois,6.0,1,0
287,68,51.6455,0.0838,Debden,NaN,6.0,1,0
288,158,51.6412,0.0558,Loughton,NaN,6.0,1,0
289,37,51.6266,0.0471,Buckhurst Hill,Buckhurst<br />Hill,5.0,1,0
290,204,51.5343,-0.0139,Pudding Mill Lane,Pudding<br />Mill Lane,2.5,1,0
291,233,51.5040,-0.1052,Southwark,NaN,1.0,1,0
292,41,51.4982,-0.0502,Canada Water,Canada<br />Water,2.0,2,0
293,43,51.5147,0.0082,Canning Town,Canning<br />Town,3.0,2,1
294,183,51.5005,0.0039,North Greenwich,North<br />Greenwich,2.5,1,0
295,64,51.4827,-0.0096,Cutty Sark,Cutty<br />Sark,2.5,1,0
296,106,51.4781,-0.0149,Greenwich,NaN,2.5,1,1
297,69,51.4740,-0.0216,Deptford Bridge,Deptford<br />Bridge,2.5,1,0
298,86,51.4693,-0.0174,Elverson Road,Elverson<br />Road,2.5,1,0
299,152,51.4657,-0.0142,Lewisham,NaN,2.5,1,1
300,174,51.4767,-0.0327,New Cross,New<br />Cross,2.0,1,1
301,175,51.4757,-0.0402,New Cross Gate,New<br />Cross<br />Gate,2.0,1,1
302,304,51.5027,0.0226,West Silvertown,West<br />Silvertown,3.0,1,0
303,307,51.5020,0.0627,King George V,King<br />George V,3.0,1,0
304,305,51.5021,0.0319,Pontoon Dock,Pontoon<br />Dock,3.0,1,0
305,306,51.5037,0.0488,London City Airport,London<br />City<br />Airport,3.0,1,0

In [38]:
ordest.FromName = ordest.apply(lambda row: row['FromName'].strip(), axis=1)

In [39]:
ordest

,From,FromName,To,ToName,Early,AM peak,Midday,PM Peak,Evening,Late,Evening Late Total,Zone
0,669,Oxford Circus,741,Victoria,28,158,2139,2978,1596,649,2245,1
1,513,Bank / Monument,728,Tottenham Court Road,94,807,1220,792,1054,297,1351,1
2,625,King's Cross St. Pancras,741,Victoria,119,1965,1887,1251,1022,244,1266,1
3,574,Euston,741,Victoria,152,1359,1691,2157,956,286,1242,1
4,674,Piccadilly Circus,670,Paddington,0,36,495,872,623,458,1081,1
5,542,Embankment,741,Victoria,124,377,742,1124,573,489,1062,1
6,625,King's Cross St. Pancras,670,Paddington,208,2458,2830,1790,846,178,1024,1
7,674,Piccadilly Circus,741,Victoria,0,0,441,673,424,568,992,1
8,751,Wembley Central,674,Piccadilly Circus,0,72,0,12,161,150,311,4
9,590,Green Park,741,Victoria,10,87,904,1368,606,311,917,1
10,669,Oxford Circus,670,Paddington,8,56,773,1146,614,218,832,1
11,574,Euston,669,Oxford Circus,64,1400,2641,721,716,0,716,1
12,631,Leicester Square,741,Victoria,0,0,348,480,323,382,705,1
13,745,Warren Street,741,Victoria,33,107,721,1456,508,142,650,1
14,708,South Kensington,741,Victoria,0,125,765,1043,431,212,643,1
15,577,Farringdon,670,Paddington,28,198,1089,1698,370,208,578,1
16,728,Tottenham Court Road,718,Charing Cross,3,21,299,439,300,274,574,1
17,669,Oxford Circus,718,Charing Cross,0,22,394,759,409,135,544,1
18,645,Moorgate,511,Baker Street,17,108,590,754,413,129,542,1
19,741,Victoria,669,Oxford Circus,197,2590,3159,1231,387,143,530,1
20,763,Whitechapel,741,Victoria,108,279,282,614,490,0,490,2
21,634,Liverpool Street,670,Paddington,127,747,912,1115,373,111,484,1
22,702,Sloane Square,741,Victoria,16,95,600,523,323,156,479,1
23,626,Knightsbridge,674,Piccadilly Circus,5,54,762,606,341,137,478,1
24,669,Oxford Circus,681,Queensway,0,0,79,73,227,230,457,1
25,634,Liverpool Street,669,Oxford Circus,102,1721,2436,1624,397,55,452,1
26,634,Liverpool Street,741,Victoria,98,556,751,633,323,126,449,1
27,593,Hammersmith (Dis),741,Victoria,53,249,432,628,222,227,449,2
28,575,Euston Square,670,Paddington,36,288,663,957,378,65,443,1
29,631,Leicester Square,728,Tottenham Court Road,0,0,444,348,235,198,433,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5619,779,Hatton Cross,631,Leicester Square,0,17,48,15,0,0,0,"5,6"
5620,779,Hatton Cross,637,Maida Vale,0,10,0,0,0,0,0,"5,6"
5621,779,Hatton Cross,641,Marylebone,0,0,0,1,0,0,0,"5,6"
5622,779,Hatton Cross,669,Oxford Circus,7,7,10,3,0,0,0,"5,6"
5623,779,Hatton Cross,670,Paddington,17,24,11,0,0,0,0,"5,6"
5624,779,Hatton Cross,674,Piccadilly Circus,7,28,57,16,0,0,0,"5,6"
5625,779,Hatton Cross,685,Regent's Park,5,0,0,0,0,0,0,"5,6"
5626,779,Hatton Cross,690,Royal Oak,0,0,5,0,0,0,0,"5,6"
5627,779,Hatton Cross,695,St. James's Park,15,39,21,0,0,0,0,"5,6"
5628,779,Hatton Cross,696,St. John's Wood,0,18,0,0,0,0,0,"5,6"
5629,779,Hatton Cross,724,Temple,0,0,1,4,0,0,0,"5,6"
5630,779,Hatton Cross,728,Tottenham Court Road,0,5,0,0,0,0,0,"5,6"
5631,779,Hatton Cross,741,Victoria,0,22,15,41,0,0,0,"5,6"
5632,779,Hatton Cross,746,Warwick Avenue,0,0,0,0,0,0,0,"5,6"
5633,779,Hatton Cross,754,Westbourne Park,0,0,0,1,0,0,0,"5,6"
5634,646,Moor Park,511,Baker Street,1,21,20,52,0,0,0,"6,7"
5635,646,Moor Park,524,Bond Street,0,9,0,0,0,0,0,"6,7"
5636,646,Moor Park,718,Charing Cross,0,1,9,45,0,0,0,"6,7"
5637,646,Moor Park,542,Embankment,0,0,0,0,0,0,0,"6,7"
5638,646,Moor Park,588,Great Portland Street,3,23,0,0,0,0,0,"6,7"
5639,646,Moor Park,590,Green Park,11,35,13,4,0,0,0,"6,7"
5640,646,Moor Park,614,Hyde Park Corner,0,27,0,0,0,0,0,"6,7"
5641,646,Moor Park,631,Leicester Square,0,14,0,20,0,0,0,"6,7"
5642,646,Moor Park,669,Oxford Circus,0,2,0,59,0,0,0,"6,7"
5643,646,Moor Park,674,Piccadilly Circus,1,5,30,0,0,0,0,"6,7"
5644,646,Moor Park,685,Regent's Park,0,3,2,0,0,0,0,"6,7"
5645,646,Moor Park,724,Temple,0,0,0,0,0,0,0,"6,7"
5646,646,Moor Park,728,Tottenham Court Road,0,0,0,10,0,0,0,"6,7"
5647,646,Moor Park,741,Victoria,1,1,0,0,0,0,0,"6,7"
5648,646,Moor Park,761,Westminster,9,45,0,0,0,0,0,"6,7"

In [41]:
ordest_locs = ordest.merge(tubelocs, left_on='FromName', right_on='name')

In [47]:
ordest_locs

,From,FromName,To,ToName,Early,AM peak,Midday,PM Peak,Evening,Late,Evening Late Total,Zone,id,latitude,longitude,name,display_name,zone,total_lines,rail
0,669,Oxford Circus,741,Victoria,28,158,2139,2978,1596,649,2245,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
1,669,Oxford Circus,670,Paddington,8,56,773,1146,614,218,832,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
2,669,Oxford Circus,718,Charing Cross,0,22,394,759,409,135,544,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
3,669,Oxford Circus,681,Queensway,0,0,79,73,227,230,457,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
4,669,Oxford Circus,641,Marylebone,0,40,478,329,320,85,405,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
5,669,Oxford Circus,746,Warwick Avenue,0,22,147,4,264,132,396,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
6,669,Oxford Circus,640,Marble Arch,0,45,317,459,257,121,378,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
7,669,Oxford Circus,674,Piccadilly Circus,0,35,567,318,230,0,230,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
8,669,Oxford Circus,774,Edgware Road (Bak),0,12,147,150,123,65,188,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
9,669,Oxford Circus,511,Baker Street,0,47,378,245,110,68,178,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
10,669,Oxford Circus,776,Pimlico,0,23,358,139,55,78,133,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
11,669,Oxford Circus,629,Lancaster Gate,0,0,94,151,77,45,122,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
12,669,Oxford Circus,754,Westbourne Park,0,0,75,52,116,0,116,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
13,669,Oxford Circus,553,Covent Garden,0,0,235,175,115,0,115,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
14,669,Oxford Circus,631,Leicester Square,0,6,135,135,97,0,97,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
15,669,Oxford Circus,637,Maida Vale,0,0,56,266,79,11,90,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
16,669,Oxford Circus,590,Green Park,0,42,424,222,80,0,80,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
17,669,Oxford Circus,728,Tottenham Court Road,0,10,122,79,46,31,77,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
18,669,Oxford Circus,542,Embankment,0,11,150,152,62,0,62,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
19,669,Oxford Circus,614,Hyde Park Corner,0,0,156,35,28,0,28,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
20,669,Oxford Circus,588,Great Portland Street,0,0,0,0,19,7,26,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
21,669,Oxford Circus,696,St. John's Wood,0,0,4,78,22,0,22,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
22,669,Oxford Circus,524,Bond Street,0,19,190,81,0,20,20,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
23,669,Oxford Circus,724,Temple,0,0,46,23,10,0,10,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
24,669,Oxford Circus,685,Regent's Park,0,0,72,26,0,0,0,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
25,669,Oxford Circus,690,Royal Oak,0,0,0,8,0,0,0,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
26,669,Oxford Circus,695,St. James's Park,1,18,144,45,0,0,0,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
27,669,Oxford Circus,761,Westminster,1,26,298,129,0,0,0,1,192,51.5150,-0.1415,Oxford Circus,Oxford<br />Circus,1.0,3,0
28,625,King's Cross St. Pancras,741,Victoria,119,1965,1887,1251,1022,244,1266,1,145,51.5308,-0.1238,King's Cross St. Pancras,King's Cross<br />St. Pancras,1.0,6,1
29,625,King's Cross St. Pancras,670,Paddington,208,2458,2830,1790,846,178,1024,1,145,51.5308,-0.1238,King's Cross St. Pancras,King's Cross<br />St. Pancras,1.0,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5414,506,Amersham,695,St. James's Park,7,27,0,0,0,0,0,9,6,51.6736,-0.6070,Amersham,NaN,10.0,1,1
5415,506,Amersham,696,St. John's Wood,12,14,0,0,0,0,0,9,6,51.6736,-0.6070,Amersham,NaN,10.0,1,1
5416,506,Amersham,724,Temple,0,13,15,0,0,0,0,9,6,51.6736,-0.6070,Amersham,NaN,10.0,1,1
5417,506,Amersham,728,Tottenham Court Road,0,1,6,0,0,0,0,9,6,51.6736,-0.6070,Amersham,NaN,10.0,1,1
5418,506,Amersham,741,Victoria,6,26,28,0,0,0,0,9,6,51.6736,-0.6070,Amersham,NaN,10.0,1,1
5419,506,Amersham,761,Westminster,2,7,0,0,0,0,0,9,6,51.6736,-0.6070,Amersham,NaN,10.0,1,1
5420,543,Chesham,511,Baker Street,2,26,0,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5421,543,Chesham,524,Bond Street,5,26,0,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5422,543,Chesham,774,Edgware Road (Bak),18,3,0,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5423,543,Chesham,588,Great Portland Street,10,36,0,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5424,543,Chesham,670,Paddington,7,6,0,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5425,543,Chesham,674,Piccadilly Circus,0,11,0,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5426,543,Chesham,724,Temple,0,17,0,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5427,543,Chesham,728,Tottenham Court Road,2,9,29,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5428,543,Chesham,741,Victoria,5,23,0,0,0,0,0,9,50,51.7052,-0.6110,Chesham,NaN,10.0,1,0
5429,646,Moor Park,511,Baker Street,1,21,20,52,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5430,646,Moor Park,524,Bond Street,0,9,0,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5431,646,Moor Park,718,Charing Cross,0,1,9,45,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5432,646,Moor Park,542,Embankment,0,0,0,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5433,646,Moor Park,588,Great Portland Street,3,23,0,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5434,646,Moor Park,590,Green Park,11,35,13,4,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5435,646,Moor Park,614,Hyde Park Corner,0,27,0,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5436,646,Moor Park,631,Leicester Square,0,14,0,20,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5437,646,Moor Park,669,Oxford Circus,0,2,0,59,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5438,646,Moor Park,674,Piccadilly Circus,1,5,30,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5439,646,Moor Park,685,Regent's Park,0,3,2,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5440,646,Moor Park,724,Temple,0,0,0,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5441,646,Moor Park,728,Tottenham Court Road,0,0,0,10,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5442,646,Moor Park,741,Victoria,1,1,0,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0
5443,646,Moor Park,761,Westminster,9,45,0,0,0,0,0,"6,7",168,51.6294,-0.4320,Moor Park,Moor<br />Park,6.5,1,0

In [240]:
stations= pd.read_csv('../stations_with_latlong.csv')

In [60]:
wards = gpd.read_file("../QGIS DATASET/ESRI/London_Ward.shp")

In [61]:
from shapely.geometry import Point

In [73]:
tubelocs['geom'] = tubelocs.apply(lambda row: Point(row['longitude'], row['latitude']), axis=1)

In [74]:
tubelocs

,id,latitude,longitude,name,display_name,zone,total_lines,rail,geom
0,1,51.5028,-0.2801,Acton Town,Acton<br />Town,3.0,2,0,POINT (-0.2801 51.5028)
1,2,51.5143,-0.0755,Aldgate,NaN,1.0,2,0,POINT (-0.0755 51.5143)
2,3,51.5154,-0.0726,Aldgate East,Aldgate<br />East,1.0,2,0,POINT (-0.0726 51.5154)
3,4,51.5107,-0.0130,All Saints,All<br />Saints,2.0,1,0,POINT (-0.013 51.5107)
4,5,51.5407,-0.2997,Alperton,NaN,4.0,1,0,POINT (-0.2997 51.5407)
5,7,51.5322,-0.1058,Angel,NaN,1.0,1,0,POINT (-0.1058 51.5322)
6,8,51.5653,-0.1353,Archway,NaN,2.5,1,0,POINT (-0.1353 51.5653)
7,9,51.6164,-0.1331,Arnos Grove,Arnos<br />Grove,4.0,1,0,POINT (-0.1331 51.6164)
8,10,51.5586,-0.1059,Arsenal,NaN,2.0,1,0,POINT (-0.1059 51.5586)
9,11,51.5226,-0.1571,Baker Street,Baker<br />Street,1.0,5,0,POINT (-0.1571 51.5226)
10,12,51.4431,-0.1525,Balham,NaN,3.0,1,1,POINT (-0.1525 51.4431)
11,13,51.5133,-0.0886,Bank,NaN,1.0,4,0,POINT (-0.0886 51.5133)
12,14,51.5204,-0.0979,Barbican,NaN,1.0,3,0,POINT (-0.0979 51.5204)
13,15,51.5396,0.0810,Barking,NaN,4.0,2,1,POINT (0.081 51.5396)
14,16,51.5856,0.0887,Barkingside,NaN,5.0,1,0,POINT (0.0887 51.5856)
15,17,51.4905,-0.2139,Barons Court,Barons<br />Court,2.0,2,0,POINT (-0.2139 51.4905)
16,18,51.5121,-0.1879,Bayswater,NaN,1.0,2,0,POINT (-0.1879 51.5121)
17,19,51.5148,0.0613,Beckton,NaN,3.0,1,0,POINT (0.0613 51.5148)
18,20,51.5087,0.0550,Beckton Park,Beckton<br />Park,3.0,1,0,POINT (0.055 51.5087)
19,21,51.5403,0.1270,Becontree,NaN,5.0,1,0,POINT (0.127 51.5403)
20,22,51.5504,-0.1642,Belsize Park,Belsize<br />Park,2.0,1,0,POINT (-0.1642 51.5504)
21,24,51.5270,-0.0549,Bethnal Green,Bethnal<br />Green,2.0,1,0,POINT (-0.0549 51.527)
22,25,51.5120,-0.1031,Blackfriars,NaN,1.0,2,0,POINT (-0.1031 51.512)
23,26,51.5867,-0.0417,Blackhorse Road,Blackhorse<br />Road,3.0,1,1,POINT (-0.0417 51.5867)
24,27,51.5079,-0.0066,Blackwall,NaN,2.0,1,0,POINT (-0.0066 51.5079)
25,28,51.5142,-0.1494,Bond Street,Bond<br />Street,1.0,2,0,POINT (-0.1494 51.5142)
26,29,51.5011,-0.0943,Borough,NaN,1.0,1,0,POINT (-0.09429999999999999 51.5011)
27,30,51.4956,-0.3250,Boston Manor,Boston<br />Manor,4.0,1,0,POINT (-0.325 51.4956)
28,31,51.6071,-0.1243,Bounds Green,Bounds<br />Green,3.5,1,0,POINT (-0.1243 51.6071)
29,32,51.5273,-0.0208,Bow Church,Bow<br />Church,2.0,1,0,POINT (-0.0208 51.5273)
...,...,...,...,...,...,...,...,...,...
276,214,51.6404,-0.4733,Rickmansworth,NaN,7.0,1,0,POINT (-0.4733 51.6404)
277,62,51.6470,-0.4412,Croxley,NaN,7.0,1,0,POINT (-0.4412 51.647)
278,280,51.6573,-0.4177,Watford,NaN,8.0,1,0,POINT (-0.4177 51.6573)
279,221,51.5606,-0.4103,Ruislip Gardens,Ruislip<br />Gardens,5.0,1,0,POINT (-0.4103 51.5606)
280,121,51.6503,-0.1943,High Barnet,High<br />Barnet,5.0,1,0,POINT (-0.1943 51.6503)
281,261,51.6302,-0.1791,Totteridge & Whetstone,Totteridge<br />& Whetstone,4.0,1,0,POINT (-0.1791 51.6302)
282,57,51.6517,-0.1496,Cockfosters,NaN,5.0,1,0,POINT (-0.1496 51.6517)
283,187,51.6476,-0.1318,Oakwood,NaN,5.0,1,0,POINT (-0.1318 51.6476)
284,232,51.6322,-0.1280,Southgate,NaN,4.0,1,0,POINT (-0.128 51.6322)
285,88,51.6937,0.1139,Epping,NaN,6.0,1,0,POINT (0.1139 51.6937)
286,256,51.6717,0.1033,Theydon Bois,Theydon<br />Bois,6.0,1,0,POINT (0.1033 51.6717)
287,68,51.6455,0.0838,Debden,NaN,6.0,1,0,POINT (0.0838 51.6455)
288,158,51.6412,0.0558,Loughton,NaN,6.0,1,0,POINT (0.0558 51.6412)
289,37,51.6266,0.0471,Buckhurst Hill,Buckhurst<br />Hill,5.0,1,0,POINT (0.0471 51.6266)
290,204,51.5343,-0.0139,Pudding Mill Lane,Pudding<br />Mill Lane,2.5,1,0,POINT (-0.0139 51.5343)
291,233,51.5040,-0.1052,Southwark,NaN,1.0,1,0,POINT (-0.1052 51.504)
292,41,51.4982,-0.0502,Canada Water,Canada<br />Water,2.0,2,0,POINT (-0.0502 51.4982)
293,43,51.5147,0.0082,Canning Town,Canning<br />Town,3.0,2,1,POINT (0.008200000000000001 51.5147)
294,183,51.5005,0.0039,North Greenwich,North<br />Greenwich,2.5,1,0,POINT (0.0039 51.5005)
295,64,51.4827,-0.0096,Cutty Sark,Cutty<br />Sark,2.5,1,0,POINT (-0.009599999999999999 51.4827)
296,106,51.4781,-0.0149,Greenwich,NaN,2.5,1,1,POINT (-0.0149 51.4781)
297,69,51.4740,-0.0216,Deptford Bridge,Deptford<br />Bridge,2.5,1,0,POINT (-0.0216 51.474)
298,86,51.4693,-0.0174,Elverson Road,Elverson<br />Road,2.5,1,0,POINT (-0.0174 51.4693)
299,152,51.4657,-0.0142,Lewisham,NaN,2.5,1,1,POINT (-0.0142 51.4657)
300,174,51.4767,-0.0327,New Cross,New<br />Cross,2.0,1,1,POINT (-0.0327 51.4767)
301,175,51.4757,-0.0402,New Cross Gate,New<br />Cross<br />Gate,2.0,1,1,POINT (-0.0402 51.4757)
302,304,51.5027,0.0226,West Silvertown,West<br />Silvertown,3.0,1,0,POINT (0.0226 51.5027)
303,307,51.5020,0.0627,King George V,King<br />George V,3.0,1,0,POINT (0.06270000000000001 51.502)
304,305,51.5021,0.0319,Pontoon Dock,Pontoon<br />Dock,3.0,1,0,POINT (0.0319 51.5021)
305,306,51.5037,0.0488,London City Airport,London<br />City<br />Airport,3.0,1,0,POINT (0.0488 51.5037)

In [91]:
tubelocs_geo = gpd.GeoDataFrame(tubelocs, geometry='geom', crs={'init' :'epsg:4326'})

In [92]:
wcrs = wards.crs
wcrs

{u'datum': u'OSGB36',
 u'k': 0.999601272,
 u'lat_0': 49,
 u'lon_0': -2,
 u'no_defs': True,
 u'proj': u'tmerc',
 u'units': u'm',
 u'x_0': 400000,
 u'y_0': -100000}

In [95]:
tubelocs_geo.to_crs(crs=wcrs, inplace=True)

In [94]:
tubelocs_geo.crs

{'init': 'epsg:4326'}

In [101]:
tubelocs_geo.columns

Index([u'id', u'latitude', u'longitude', u'name', u'display_name', u'zone',
       u'total_lines', u'rail', u'geom'],
      dtype='object')

In [102]:
wards.columns

Index([   u'BOROUGH',   u'GSS_CODE',   u'HECTARES',  u'LB_GSS_CD',
             u'NAME', u'NONLD_AREA',    u'POLY_ID',   u'geometry'],
      dtype='object')

In [107]:
tubelocs_geo.rename(columns={'geom':'geometry'}, inplace=True)

In [109]:
tube_wards = gpd.sjoin(tubelocs_geo, wards, how='left')

In [111]:
ordest_tubewards = ordest_locs = ordest.merge(tube_wards, left_on='FromName', right_on='name')

In [112]:
ordest_tubewards

,From,FromName,To,ToName,Early,AM peak,Midday,PM Peak,Evening,Late,...,rail,geometry,index_right,BOROUGH,GSS_CODE,HECTARES,LB_GSS_CD,NAME,NONLD_AREA,POLY_ID
0,669,Oxford Circus,741,Victoria,28,158,2139,2978,1596,649,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
1,669,Oxford Circus,670,Paddington,8,56,773,1146,614,218,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
2,669,Oxford Circus,718,Charing Cross,0,22,394,759,409,135,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
3,669,Oxford Circus,681,Queensway,0,0,79,73,227,230,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
4,669,Oxford Circus,641,Marylebone,0,40,478,329,320,85,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
5,669,Oxford Circus,746,Warwick Avenue,0,22,147,4,264,132,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
6,669,Oxford Circus,640,Marble Arch,0,45,317,459,257,121,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
7,669,Oxford Circus,674,Piccadilly Circus,0,35,567,318,230,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
8,669,Oxford Circus,774,Edgware Road (Bak),0,12,147,150,123,65,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
9,669,Oxford Circus,511,Baker Street,0,47,378,245,110,68,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
10,669,Oxford Circus,776,Pimlico,0,23,358,139,55,78,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
11,669,Oxford Circus,629,Lancaster Gate,0,0,94,151,77,45,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
12,669,Oxford Circus,754,Westbourne Park,0,0,75,52,116,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
13,669,Oxford Circus,553,Covent Garden,0,0,235,175,115,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
14,669,Oxford Circus,631,Leicester Square,0,6,135,135,97,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
15,669,Oxford Circus,637,Maida Vale,0,0,56,266,79,11,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
16,669,Oxford Circus,590,Green Park,0,42,424,222,80,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
17,669,Oxford Circus,728,Tottenham Court Road,0,10,122,79,46,31,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
18,669,Oxford Circus,542,Embankment,0,11,150,152,62,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
19,669,Oxford Circus,614,Hyde Park Corner,0,0,156,35,28,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
20,669,Oxford Circus,588,Great Portland Street,0,0,0,0,19,7,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
21,669,Oxford Circus,696,St. John's Wood,0,0,4,78,22,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
22,669,Oxford Circus,524,Bond Street,0,19,190,81,0,20,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
23,669,Oxford Circus,724,Temple,0,0,46,23,10,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
24,669,Oxford Circus,685,Regent's Park,0,0,72,26,0,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
25,669,Oxford Circus,690,Royal Oak,0,0,0,8,0,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
26,669,Oxford Circus,695,St. James's Park,1,18,144,45,0,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
27,669,Oxford Circus,761,Westminster,1,26,298,129,0,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
28,625,King's Cross St. Pancras,741,Victoria,119,1965,1887,1251,1022,244,...,1,POINT (530239.6129378686 182989.3652701066),503.0,Camden,E05000143,139.889,E09000007,St. Pancras and Somers Town,0.0,117290.0
29,625,King's Cross St. Pancras,670,Paddington,208,2458,2830,1790,846,178,...,1,POINT (530239.6129378686 182989.3652701066),503.0,Camden,E05000143,139.889,E09000007,St. Pancras and Somers Town,0.0,117290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5414,506,Amersham,695,St. James's Park,7,27,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5415,506,Amersham,696,St. John's Wood,12,14,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5416,506,Amersham,724,Temple,0,13,15,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5417,506,Amersham,728,Tottenham Court Road,0,1,6,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5418,506,Amersham,741,Victoria,6,26,28,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5419,506,Amersham,761,Westminster,2,7,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5420,543,Chesham,511,Baker Street,2,26,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5421,543,Chesham,524,Bond Street,5,26,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5422,543,Chesham,774,Edgware Road (Bak),18,3,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5423,543,Chesham,588,Great Portland Street,10,36,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5424,543,Chesham,670,Paddington,7,6,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5425,543,Chesham,674,Piccadilly Circus,0,11,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5426,543,Chesham,724,Temple,0,17,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5427,543,Chesham,728,Tottenham Court Road,2,9,29,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5428,543,Chesham,741,Victoria,5,23,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5429,646,Moor Park,511,Baker Street,1,21,20,52,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5430,646,Moor Park,524,Bond Street,0,9,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5431,646,Moor Park,718,Charing Cross,0,1,9,45,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5432,646,Moor Park,542,Embankment,0,0,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5433,646,Moor Park,588,Great Portland Street,3,23,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5434,646,Moor Park,590,Green Park,11,35,13,4,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5435,646,Moor Park,614,Hyde Park Corner,0,27,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5436,646,Moor Park,631,Leicester Square,0,14,0,20,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5437,646,Moor Park,669,Oxford Circus,0,2,0,59,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5438,646,Moor Park,674,Piccadilly Circus,1,5,30,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5439,646,Moor Park,685,Regent's Park,0,3,2,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5440,646,Moor Park,724,Temple,0,0,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5441,646,Moor Park,728,Tottenham Court Road,0,0,0,10,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5442,646,Moor Park,741,Victoria,1,1,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5443,646,Moor Park,761,Westminster,9,45,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
ordest_tubewards[ordest_tubewards.NAME.isnull()]

,From,FromName,To,ToName,Early,AM peak,Midday,PM Peak,Evening,Late,...,rail,geometry,index_right,BOROUGH,GSS_CODE,HECTARES,LB_GSS_CD,NAME,NONLD_AREA,POLY_ID
2613,636,Loughton,511,Baker Street,2,28,7,0,13,26,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2614,636,Loughton,681,Queensway,0,0,0,0,0,12,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2615,636,Loughton,728,Tottenham Court Road,0,2,0,0,0,3,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2616,636,Loughton,640,Marble Arch,23,33,0,0,7,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2617,636,Loughton,524,Bond Street,66,140,27,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2618,636,Loughton,718,Charing Cross,0,11,0,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2619,636,Loughton,774,Edgware Road (Bak),0,0,48,6,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2620,636,Loughton,542,Embankment,3,35,0,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2621,636,Loughton,590,Green Park,0,112,0,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2622,636,Loughton,614,Hyde Park Corner,0,6,0,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2623,636,Loughton,631,Leicester Square,0,0,1,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2624,636,Loughton,637,Maida Vale,0,0,16,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2625,636,Loughton,669,Oxford Circus,22,222,18,56,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2626,636,Loughton,674,Piccadilly Circus,0,51,0,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2627,636,Loughton,776,Pimlico,6,12,0,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2628,636,Loughton,695,St. James's Park,6,26,0,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2629,636,Loughton,741,Victoria,2,7,0,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2630,636,Loughton,761,Westminster,3,52,30,0,0,0,...,0,POINT (542351.2028341304 195600.8043745184),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2718,688,Roding Valley,669,Oxford Circus,0,17,0,0,0,23,...,0,POINT (541602.8177129661 192897.709572898),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2719,688,Roding Valley,524,Bond Street,0,10,0,0,0,0,...,0,POINT (541602.8177129661 192897.709572898),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2720,688,Roding Valley,542,Embankment,32,4,0,0,0,0,...,0,POINT (541602.8177129661 192897.709572898),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2721,688,Roding Valley,641,Marylebone,0,8,0,0,0,0,...,0,POINT (541602.8177129661 192897.709572898),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2722,688,Roding Valley,685,Regent's Park,0,9,0,0,0,0,...,0,POINT (541602.8177129661 192897.709572898),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2723,688,Roding Valley,728,Tottenham Court Road,0,0,0,0,0,0,...,0,POINT (541602.8177129661 192897.709572898),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2724,688,Roding Valley,741,Victoria,0,0,24,0,0,0,...,0,POINT (541602.8177129661 192897.709572898),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3852,544,Chigwell,640,Marble Arch,0,5,0,0,0,4,...,0,POINT (543788.4811591089 193026.0930135345),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3853,544,Chigwell,669,Oxford Circus,0,25,0,0,0,1,...,0,POINT (543788.4811591089 193026.0930135345),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3854,544,Chigwell,524,Bond Street,0,1,0,0,0,0,...,0,POINT (543788.4811591089 193026.0930135345),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3855,544,Chigwell,553,Covent Garden,0,0,0,2,0,0,...,0,POINT (543788.4811591089 193026.0930135345),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3856,544,Chigwell,588,Great Portland Street,0,4,0,0,0,0,...,0,POINT (543788.4811591089 193026.0930135345),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5414,506,Amersham,695,St. James's Park,7,27,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5415,506,Amersham,696,St. John's Wood,12,14,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5416,506,Amersham,724,Temple,0,13,15,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5417,506,Amersham,728,Tottenham Court Road,0,1,6,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5418,506,Amersham,741,Victoria,6,26,28,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5419,506,Amersham,761,Westminster,2,7,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5420,543,Chesham,511,Baker Street,2,26,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5421,543,Chesham,524,Bond Street,5,26,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5422,543,Chesham,774,Edgware Road (Bak),18,3,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5423,543,Chesham,588,Great Portland Street,10,36,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5424,543,Chesham,670,Paddington,7,6,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5425,543,Chesham,674,Piccadilly Circus,0,11,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5426,543,Chesham,724,Temple,0,17,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5427,543,Chesham,728,Tottenham Court Road,2,9,29,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5428,543,Chesham,741,Victoria,5,23,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5429,646,Moor Park,511,Baker Street,1,21,20,52,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5430,646,Moor Park,524,Bond Street,0,9,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5431,646,Moor Park,718,Charing Cross,0,1,9,45,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5432,646,Moor Park,542,Embankment,0,0,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5433,646,Moor Park,588,Great Portland Street,3,23,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5434,646,Moor Park,590,Green Park,11,35,13,4,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5435,646,Moor Park,614,Hyde Park Corner,0,27,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5436,646,Moor Park,631,Leicester Square,0,14,0,20,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5437,646,Moor Park,669,Oxford Circus,0,2,0,59,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5438,646,Moor Park,674,Piccadilly Circus,1,5,30,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5439,646,Moor Park,685,Regent's Park,0,3,2,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5440,646,Moor Park,724,Temple,0,0,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5441,646,Moor Park,728,Tottenham Court Road,0,0,0,10,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5442,646,Moor Park,741,Victoria,1,1,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5443,646,Moor Park,761,Westminster,9,45,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
ordest_tubewards

,From,FromName,To,ToName,Early,AM peak,Midday,PM Peak,Evening,Late,...,rail,geometry,index_right,BOROUGH,GSS_CODE,HECTARES,LB_GSS_CD,NAME,NONLD_AREA,POLY_ID
0,669,Oxford Circus,741,Victoria,28,158,2139,2978,1596,649,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
1,669,Oxford Circus,670,Paddington,8,56,773,1146,614,218,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
2,669,Oxford Circus,718,Charing Cross,0,22,394,759,409,135,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
3,669,Oxford Circus,681,Queensway,0,0,79,73,227,230,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
4,669,Oxford Circus,641,Marylebone,0,40,478,329,320,85,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
5,669,Oxford Circus,746,Warwick Avenue,0,22,147,4,264,132,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
6,669,Oxford Circus,640,Marble Arch,0,45,317,459,257,121,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
7,669,Oxford Circus,674,Piccadilly Circus,0,35,567,318,230,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
8,669,Oxford Circus,774,Edgware Road (Bak),0,12,147,150,123,65,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
9,669,Oxford Circus,511,Baker Street,0,47,378,245,110,68,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
10,669,Oxford Circus,776,Pimlico,0,23,358,139,55,78,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
11,669,Oxford Circus,629,Lancaster Gate,0,0,94,151,77,45,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
12,669,Oxford Circus,754,Westbourne Park,0,0,75,52,116,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
13,669,Oxford Circus,553,Covent Garden,0,0,235,175,115,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
14,669,Oxford Circus,631,Leicester Square,0,6,135,135,97,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
15,669,Oxford Circus,637,Maida Vale,0,0,56,266,79,11,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
16,669,Oxford Circus,590,Green Park,0,42,424,222,80,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
17,669,Oxford Circus,728,Tottenham Court Road,0,10,122,79,46,31,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
18,669,Oxford Circus,542,Embankment,0,11,150,152,62,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
19,669,Oxford Circus,614,Hyde Park Corner,0,0,156,35,28,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
20,669,Oxford Circus,588,Great Portland Street,0,0,0,0,19,7,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
21,669,Oxford Circus,696,St. John's Wood,0,0,4,78,22,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
22,669,Oxford Circus,524,Bond Street,0,19,190,81,0,20,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
23,669,Oxford Circus,724,Temple,0,0,46,23,10,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
24,669,Oxford Circus,685,Regent's Park,0,0,72,26,0,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
25,669,Oxford Circus,690,Royal Oak,0,0,0,8,0,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
26,669,Oxford Circus,695,St. James's Park,1,18,144,45,0,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
27,669,Oxford Circus,761,Westminster,1,26,298,129,0,0,...,0,POINT (529056.5723865986 181201.0109328986),484.0,Westminster,E05000649,199.973,E09000033,West End,0.0,50723.0
28,625,King's Cross St. Pancras,741,Victoria,119,1965,1887,1251,1022,244,...,1,POINT (530239.6129378686 182989.3652701066),503.0,Camden,E05000143,139.889,E09000007,St. Pancras and Somers Town,0.0,117290.0
29,625,King's Cross St. Pancras,670,Paddington,208,2458,2830,1790,846,178,...,1,POINT (530239.6129378686 182989.3652701066),503.0,Camden,E05000143,139.889,E09000007,St. Pancras and Somers Town,0.0,117290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5414,506,Amersham,695,St. James's Park,7,27,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5415,506,Amersham,696,St. John's Wood,12,14,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5416,506,Amersham,724,Temple,0,13,15,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5417,506,Amersham,728,Tottenham Court Road,0,1,6,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5418,506,Amersham,741,Victoria,6,26,28,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5419,506,Amersham,761,Westminster,2,7,0,0,0,0,...,1,POINT (496421.5009284438 198121.6006899417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5420,543,Chesham,511,Baker Street,2,26,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5421,543,Chesham,524,Bond Street,5,26,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5422,543,Chesham,774,Edgware Road (Bak),18,3,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5423,543,Chesham,588,Great Portland Street,10,36,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5424,543,Chesham,670,Paddington,7,6,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5425,543,Chesham,674,Piccadilly Circus,0,11,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5426,543,Chesham,724,Temple,0,17,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5427,543,Chesham,728,Tottenham Court Road,2,9,29,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5428,543,Chesham,741,Victoria,5,23,0,0,0,0,...,0,POINT (496078.066499996 201630.6537276371),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5429,646,Moor Park,511,Baker Street,1,21,20,52,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5430,646,Moor Park,524,Bond Street,0,9,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5431,646,Moor Park,718,Charing Cross,0,1,9,45,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5432,646,Moor Park,542,Embankment,0,0,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5433,646,Moor Park,588,Great Portland Street,3,23,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5434,646,Moor Park,590,Green Park,11,35,13,4,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5435,646,Moor Park,614,Hyde Park Corner,0,27,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5436,646,Moor Park,631,Leicester Square,0,14,0,20,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5437,646,Moor Park,669,Oxford Circus,0,2,0,59,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5438,646,Moor Park,674,Piccadilly Circus,1,5,30,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5439,646,Moor Park,685,Regent's Park,0,3,2,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5440,646,Moor Park,724,Temple,0,0,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5441,646,Moor Park,728,Tottenham Court Road,0,0,0,10,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5442,646,Moor Park,741,Victoria,1,1,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5443,646,Moor Park,761,Westminster,9,45,0,0,0,0,...,0,POINT (508627.4566057562 193451.4176552131),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [122]:
gr

,Ward,Career Climbers,City Sophisticates,Comfortable Seniors,Countryside Communities,Difficult Circumstances,Executive Wealth,Lavish Lifestyles,Mature Money,Modest Means,...,Steady Neighbourhoods,Striving Families,Struggling Estates,Student Life,Successful Suburbs,Young Hardship,Code,LAD code,Borough,2012/13
0,Abbey,48.0,99.0,NaN,NaN,6.0,3.0,NaN,NaN,30.0,...,8.0,NaN,102.0,52.0,4.0,NaN,E05000026,E09000002,Barking and Dagenham,38870
1,Abbey,48.0,99.0,NaN,NaN,6.0,3.0,NaN,NaN,30.0,...,8.0,NaN,102.0,52.0,4.0,NaN,E05000455,E09000024,Merton,62540
2,Abbey Road,5.0,197.0,1.0,NaN,1.0,NaN,93.0,NaN,NaN,...,NaN,NaN,6.0,3.0,NaN,NaN,E05000630,E09000033,Westminster,90170
3,Abbey Wood,11.0,NaN,NaN,NaN,55.0,NaN,NaN,NaN,2.0,...,43.0,7.0,100.0,14.0,NaN,5.0,E05000214,E09000011,Greenwich,39630
4,Abingdon,NaN,116.0,NaN,NaN,NaN,NaN,96.0,NaN,NaN,...,NaN,NaN,8.0,1.0,NaN,NaN,E05000382,E09000020,Kensington and Chelsea,113950
5,Acton Central,64.0,78.0,1.0,NaN,NaN,27.0,NaN,3.0,NaN,...,5.0,NaN,33.0,20.0,22.0,NaN,E05000170,E09000009,Ealing,46260
6,Addiscombe,59.0,22.0,NaN,NaN,5.0,3.0,NaN,NaN,NaN,...,33.0,NaN,21.0,26.0,5.0,4.0,E05000146,E09000008,Croydon,46520
7,Addison,1.0,128.0,NaN,NaN,NaN,NaN,9.0,NaN,NaN,...,NaN,NaN,21.0,1.0,NaN,NaN,E05000250,E09000013,Hammersmith and Fulham,63150
8,Aldborough,25.0,2.0,1.0,NaN,5.0,5.0,NaN,2.0,11.0,...,77.0,NaN,26.0,5.0,48.0,7.0,E05000495,E09000026,Redbridge,45980
9,Alexandra,16.0,92.0,1.0,NaN,1.0,97.0,3.0,30.0,5.0,...,24.0,NaN,6.0,2.0,10.0,1.0,E05000266,E09000014,Haringey,69550
10,Alexandra,16.0,92.0,1.0,NaN,1.0,97.0,3.0,30.0,5.0,...,24.0,NaN,6.0,2.0,10.0,1.0,E05000400,E09000021,Kingston upon Thames,53150
11,Alibon,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,2.0,7.0,107.0,1.0,NaN,16.0,E05000027,E09000002,Barking and Dagenham,37290
12,Alperton,20.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,47.0,...,14.0,4.0,22.0,25.0,54.0,5.0,E05000085,E09000005,Brent,38550
13,Ashburton,12.0,NaN,1.0,NaN,8.0,49.0,NaN,33.0,1.0,...,77.0,12.0,43.0,NaN,10.0,2.0,E05000147,E09000008,Croydon,47220
14,Askew,17.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,56.0,6.0,NaN,NaN,E05000251,E09000013,Hammersmith and Fulham,54390
15,Avonmore and Brook Green,NaN,146.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,...,NaN,NaN,30.0,NaN,NaN,NaN,E05000252,E09000013,Hammersmith and Fulham,62140
16,Balham,14.0,201.0,NaN,NaN,NaN,12.0,21.0,NaN,NaN,...,NaN,NaN,8.0,3.0,NaN,NaN,E05000610,E09000032,Wandsworth,76280
17,Barkingside,35.0,NaN,2.0,NaN,NaN,12.0,NaN,10.0,1.0,...,47.0,NaN,7.0,3.0,52.0,2.0,E05000496,E09000026,Redbridge,49040
18,Barnehurst,3.0,NaN,2.0,NaN,2.0,15.0,NaN,51.0,12.0,...,49.0,9.0,4.0,2.0,2.0,6.0,E05000064,E09000004,Bexley,45990
19,Barnes,1.0,78.0,1.0,NaN,1.0,23.0,96.0,NaN,NaN,...,1.0,1.0,25.0,NaN,1.0,NaN,E05000516,E09000027,Richmond upon Thames,80160
20,Barnhill,43.0,2.0,1.0,NaN,21.0,74.0,5.0,4.0,13.0,...,17.0,11.0,95.0,35.0,154.0,15.0,E05000086,E09000005,Brent,42740
21,Barnhill,43.0,2.0,1.0,NaN,21.0,74.0,5.0,4.0,13.0,...,17.0,11.0,95.0,35.0,154.0,15.0,E05000324,E09000017,Hillingdon,38450
22,Barnsbury,1.0,172.0,NaN,NaN,2.0,NaN,8.0,NaN,NaN,...,NaN,NaN,74.0,6.0,NaN,NaN,E05000366,E09000019,Islington,62770
23,Bayswater,NaN,154.0,NaN,NaN,NaN,NaN,13.0,NaN,NaN,...,NaN,NaN,5.0,1.0,NaN,NaN,E05000631,E09000033,Westminster,85610
24,Beckton,25.0,2.0,NaN,NaN,13.0,NaN,NaN,NaN,1.0,...,10.0,NaN,95.0,21.0,12.0,13.0,E05000475,E09000025,Newham,40180
25,Becontree,1.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.0,NaN,110.0,17.0,6.0,8.0,E05000028,E09000002,Barking and Dagenham,37860
26,Beddington North,13.0,NaN,NaN,NaN,3.0,12.0,NaN,37.0,1.0,...,63.0,14.0,5.0,NaN,1.0,7.0,E05000555,E09000029,Sutton,48270
27,Beddington South,6.0,NaN,NaN,NaN,49.0,77.0,5.0,5.0,5.0,...,4.0,2.0,17.0,1.0,7.0,2.0,E05000556,E09000029,Sutton,43390
28,Bedfont,12.0,NaN,NaN,NaN,33.0,NaN,NaN,3.0,9.0,...,28.0,32.0,15.0,NaN,20.0,15.0,E05000346,E09000018,Hounslow,40040
29,Bedford,14.0,168.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,2.0,NaN,NaN,E05000611,E09000032,Wandsworth,64470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569,West Ham,15.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,NaN,139.0,8.0,NaN,NaN,E05000494,E09000025,Newham,38130
570,West Hampstead,1.0,188.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,24.0,3.0,NaN,NaN,E05000145,E09000007,Camden,72450
571,West Harrow,32.0,11.0,NaN,NaN,5.0,20.0,NaN,4.0,NaN,...,16.0,NaN,7.0,6.0,52.0,NaN,E05000305,E09000015,Harrow,50910
572,West Hendon,78.0,11.0,NaN,NaN,9.0,73.0,19.0,2.0,2.0,...,5.0,NaN,33.0,46.0,38.0,6.0,E05000062,E09000003,Barnet,46620
573,West Hill,84.0,76.0,NaN,NaN,1.0,35.0,9.0,3.0,NaN,...,1.0,1.0,30.0,34.0,NaN,NaN,E05000628,E09000032,Wandsworth,55010
574,West Putney,29.0,95.0,1.0,NaN,3.0,43.0,47.0,1.0,2.0,...,13.0,NaN,34.0,18.0,NaN,2.0,E05000629,E09000032,Wandsworth,59490
575,West Ruislip,68.0,NaN,1.0,NaN,7.0,96.0,8.0,26.0,3.0,...,16.0,3.0,NaN,NaN,17.0,4.0,E05000343,E09000017,Hillingdon,53580
576,West Thornton,19.0,2.0,NaN,NaN,4.0,NaN,NaN,NaN,10.0,...,73.0,1.0,57.0,20.0,22.0,6.0,E05000168,E09000008,Croydon,39350
577,West Twickenham,32.0,43.0,NaN,NaN,5.0,34.0,NaN,11.0,1.0,...,29.0,3.0,13.0,2.0,1.0,NaN,E05000532,E09000027,Richmond upon Thames,62320
578,West Wickham,13.0,NaN,2.0,NaN,8.0,143.0,6.0,37.0,6.0,...,37.0,2.0,NaN,NaN,NaN,1.0,E05000127,E09000006,Bromley,59830
579,Westbourne,2.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,110.0,1.0,NaN,NaN,E05000648,E09000033,Westminster,53730
580,Whalebone,6.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN,5.0,...,81.0,NaN,21.0,15.0,3.0,15.0,E05000042,E09000002,Barking and Dagenham,42530
581,White Hart Lane,6.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,8.0,5.0,155.0,10.0,NaN,4.0,E05000283,E09000014,Haringey,35340
582,Whitechapel,16.0,176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,116.0,23.0,2.0,NaN,E05000589,E09000030,Tower Hamlets,49140
583,Whitefoot,8.0,1.0,2.0,NaN,14.0,NaN,NaN,7.0,2.0,...,56.0,1.0,77.0,10.0,6.0,2.0,E05000454,E09000023,Lewisham,39620
584,Whitton,25.0,1.0,NaN,NaN,3.0,36.0,NaN,29.0,NaN,...,29.0,NaN,10.0,9.0,3.0,1.0,E05000533,E09000027,Richmond upon Thames,57850
585,Willesden Green,105.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,61.0,29.0,1.0,1.0,E05000105,E09000005,Brent,38710
586,William Morris,34.0,10.0,NaN,NaN,2.0,NaN,NaN,NaN,1.0,...,5.0,NaN,57.0,6.0,1.0,1.0,E05000608,E09000031,Waltham Forest,41860
587,Wimbledon Park,16.0,93.0,NaN,NaN,NaN,15.0,16.0,NaN,NaN,...,1.0,NaN,12.0,3.0,NaN,NaN,E05000474,E09000024,Merton,71450
588,Winchmore Hill,45.0,36.0,1.0,NaN,2.0,106.0,18.0,6.0,1.0,...,11.0,NaN,7.0,4.0,NaN,4.0,E05000213,E09000010,Enfield,58520
589,Wood Street,52.0,6.0,1.0,NaN,1.0,4.0,NaN,NaN,2.0,...,19.0,NaN,69.0,27.0,3.0,NaN,E05000609,E09000031,Waltham Forest,41930
590,Woodhouse,139.0,51.0,1.0,NaN,7.0,57.0,NaN,14.0,1.0,...,20.0,1.0,20.0,14.0,20.0,1.0,E05000063,E09000003,Barnet,51100
591,Woodside,107.0,25.0,NaN,NaN,11.0,NaN,NaN,2.0,NaN,...,62.0,1.0,129.0,54.0,2.0,12.0,E05000169,E09000008,Croydon,41170
592,Woodside,107.0,25.0,NaN,NaN,11.0,NaN,NaN,2.0,NaN,...,62.0,1.0,129.0,54.0,2.0,12.0,E05000284,E09000014,Haringey,41420
593,Woolwich Common,40.0,6.0,NaN,NaN,23.0,NaN,NaN,NaN,NaN,...,6.0,NaN,138.0,32.0,NaN,11.0,E05000229,E09000011,Greenwich,38090
594,Woolwich Riverside,15.0,46.0,NaN,NaN,51.0,1.0,NaN,NaN,NaN,...,9.0,1.0,139.0,50.0,NaN,1.0,E05000230,E09000011,Greenwich,42080
595,Worcester Park,44.0,6.0,2.0,NaN,8.0,27.0,NaN,17.0,9.0,...,39.0,1.0,9.0,5.0,NaN,4.0,E05000572,E09000029,Sutton,50070
596,Wormholt and White City,20.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,102.0,1.0,1.0,NaN,E05000265,E09000013,Hammersmith and Fulham,44740
597,Yeading,13.0,1.0,NaN,NaN,16.0,6.0,NaN,NaN,6.0,...,14.0,3.0,70.0,2.0,63.0,11.0,E05000344,E09000017,Hillingdon,40180
598,Yiewsley,25.0,NaN,NaN,NaN,19.0,NaN,NaN,1.0,10.0,...,15.0,46.0,32.0,22.0,25.0,23.0,E05000345,E09000017,Hillingdon,39100

In [124]:
ordest_income = ordest_tubewards.merge(gr, left_on=ordest_tubewards.NAME, right_on=gr.Ward)

In [133]:
ordest_income.columns

Index([                   u'From',                u'FromName',
                            u'To',                  u'ToName',
                    u'Early     ',              u'AM peak   ',
                    u'Midday    ',              u'PM Peak   ',
                    u'Evening   ',              u'Late      ',
            u'Evening Late Total',                    u'Zone',
                            u'id',                u'latitude',
                     u'longitude',                    u'name',
                  u'display_name',                    u'zone',
                   u'total_lines',                    u'rail',
                      u'geometry',             u'index_right',
                       u'BOROUGH',                u'GSS_CODE',
                      u'HECTARES',               u'LB_GSS_CD',
                          u'NAME',              u'NONLD_AREA',
                       u'POLY_ID',                    u'Ward',
               u'Career Climbers',      u'City Sophisticates',
           u'Comfortable Seniors', u'Countryside Communities',
       u'Difficult Circumstances',        u'Executive Wealth',
             u'Lavish Lifestyles',            u'Mature Money',
                  u'Modest Means',  u'Not Private Households',
                  u'Not Recorded',       u'Poorer Pensioners',
                  u'Starting Out',   u'Steady Neighbourhoods',
             u'Striving Families',      u'Struggling Estates',
                  u'Student Life',      u'Successful Suburbs',
                u'Young Hardship',                    u'Code',
                      u'LAD code',                 u'Borough',
                       u'2012/13'],
      dtype='object')

In [134]:
ordest_income['eveningwealth']= ordest_income.apply(lambda row: row['2012/13']*row['Evening   '], axis=1)

In [135]:
ordest_income['nitewealth']= ordest_income.apply(lambda row: row['2012/13']*row['Late      '], axis=1)

In [136]:
ordest_income

,From,FromName,To,ToName,Early,AM peak,Midday,PM Peak,Evening,Late,...,Struggling Estates,Student Life,Successful Suburbs,Young Hardship,Code,LAD code,Borough,2012/13,eveningwealth,nitewealth
0,669,Oxford Circus,741,Victoria,28,158,2139,2978,1596,649,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,153120240,62265060
1,669,Oxford Circus,670,Paddington,8,56,773,1146,614,218,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,58907160,20914920
2,669,Oxford Circus,718,Charing Cross,0,22,394,759,409,135,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,39239460,12951900
3,669,Oxford Circus,681,Queensway,0,0,79,73,227,230,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,21778380,22066200
4,669,Oxford Circus,641,Marylebone,0,40,478,329,320,85,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,30700800,8154900
5,669,Oxford Circus,746,Warwick Avenue,0,22,147,4,264,132,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,25328160,12664080
6,669,Oxford Circus,640,Marble Arch,0,45,317,459,257,121,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,24656580,11608740
7,669,Oxford Circus,674,Piccadilly Circus,0,35,567,318,230,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,22066200,0
8,669,Oxford Circus,774,Edgware Road (Bak),0,12,147,150,123,65,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,11800620,6236100
9,669,Oxford Circus,511,Baker Street,0,47,378,245,110,68,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,10553400,6523920
10,669,Oxford Circus,776,Pimlico,0,23,358,139,55,78,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,5276700,7483320
11,669,Oxford Circus,629,Lancaster Gate,0,0,94,151,77,45,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,7387380,4317300
12,669,Oxford Circus,754,Westbourne Park,0,0,75,52,116,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,11129040,0
13,669,Oxford Circus,553,Covent Garden,0,0,235,175,115,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,11033100,0
14,669,Oxford Circus,631,Leicester Square,0,6,135,135,97,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,9306180,0
15,669,Oxford Circus,637,Maida Vale,0,0,56,266,79,11,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,7579260,1055340
16,669,Oxford Circus,590,Green Park,0,42,424,222,80,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,7675200,0
17,669,Oxford Circus,728,Tottenham Court Road,0,10,122,79,46,31,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,4413240,2974140
18,669,Oxford Circus,542,Embankment,0,11,150,152,62,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,5948280,0
19,669,Oxford Circus,614,Hyde Park Corner,0,0,156,35,28,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,2686320,0
20,669,Oxford Circus,588,Great Portland Street,0,0,0,0,19,7,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,1822860,671580
21,669,Oxford Circus,696,St. John's Wood,0,0,4,78,22,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,2110680,0
22,669,Oxford Circus,524,Bond Street,0,19,190,81,0,20,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,0,1918800
23,669,Oxford Circus,724,Temple,0,0,46,23,10,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,959400,0
24,669,Oxford Circus,685,Regent's Park,0,0,72,26,0,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,0,0
25,669,Oxford Circus,690,Royal Oak,0,0,0,8,0,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,0,0
26,669,Oxford Circus,695,St. James's Park,1,18,144,45,0,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,0,0
27,669,Oxford Circus,761,Westminster,1,26,298,129,0,0,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,0,0
28,728,Tottenham Court Road,718,Charing Cross,3,21,299,439,300,274,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,28782000,26287560
29,728,Tottenham Court Road,741,Victoria,0,35,486,466,190,173,...,84.0,70.0,NaN,NaN,E05000649,E09000033,Westminster,95940,18228600,16597620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4634,661,Northwood,774,Edgware Road (Bak),0,3,0,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4635,661,Northwood,542,Embankment,6,15,0,7,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4636,661,Northwood,588,Great Portland Street,3,81,2,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4637,661,Northwood,590,Green Park,2,40,15,16,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4638,661,Northwood,641,Marylebone,4,4,0,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4639,661,Northwood,669,Oxford Circus,15,38,9,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4640,661,Northwood,670,Paddington,12,7,45,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4641,661,Northwood,674,Piccadilly Circus,7,13,0,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4642,661,Northwood,776,Pimlico,0,2,0,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4643,661,Northwood,690,Royal Oak,4,31,0,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4644,661,Northwood,695,St. James's Park,9,13,0,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4645,661,Northwood,724,Temple,0,12,0,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4646,661,Northwood,728,Tottenham Court Road,0,4,0,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4647,661,Northwood,741,Victoria,4,58,35,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4648,661,Northwood,754,Westbourne Park,0,0,0,12,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4649,661,Northwood,761,Westminster,8,19,8,0,0,0,...,1.0,1.0,9.0,3.0,E05000335,E09000017,Hillingdon,57970,0,0
4650,693,Ruislip Manor,511,Baker Street,8,53,0,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4651,693,Ruislip Manor,524,Bond Street,0,16,4,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4652,693,Ruislip Manor,718,Charing Cross,7,8,0,18,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4653,693,Ruislip Manor,774,Edgware Road (Bak),0,0,12,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4654,693,Ruislip Manor,588,Great Portland Street,7,30,0,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4655,693,Ruislip Manor,590,Green Park,5,27,0,17,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4656,693,Ruislip Manor,631,Leicester Square,0,8,8,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4657,693,Ruislip Manor,669,Oxford Circus,0,8,6,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4658,693,Ruislip Manor,674,Piccadilly Circus,0,12,0,57,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4659,693,Ruislip Manor,776,Pimlico,0,5,0,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4660,693,Ruislip Manor,695,St. James's Park,0,19,0,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4661,693,Ruislip Manor,696,St. John's Wood,0,0,4,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4662,693,Ruislip Manor,741,Victoria,9,22,8,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0
4663,693,Ruislip Manor,761,Westminster,0,8,0,0,0,0,...,2.0,4.0,7.0,5.0,E05000334,E09000017,Hillingdon,53570,0,0

In [138]:
evening_wealth = ordest_income.groupby(ordest_income.ToName).agg({'eveningwealth':'sum'})

                                eveningwealth
ToName
Baker Street                        108630980
Bayswater                            64530270
Bond Street                         102945000
Charing Cross                       221256620
Covent Garden                       113467260
Edgware Road (Bak)                   22214660
Edgware Road (Cir)                   41814770
Embankment                          102871350
Great Portland Street                20112750
Green Park                          148449780
Hyde Park Corner                     34882590
Lancaster Gate                       48008350
Leicester Square                    294643410
Maida Vale                           45270010
Marble Arch                          74697850
Marylebone                          100666200
Oxford Circus                       347670130
Paddington                          371469970
Piccadilly Circus                   295659360
Pimlico                              96755910
Queensway                            75228270
Regent's Park                         9737460
Royal Oak                            21420340
St. James's Park                     32263140
St. John's Wood                      75242290
Temple                               15017030
Tottenham Court Road                190127280
Victoria                            774668570
Warwick Avenue                       67057180
Westbourne Park                      29318730
Westminster                          62325740

In [142]:
nite_wealth = ordest_income.groupby(ordest_income.ToName).agg({'nitewealth':'sum'})

In [145]:
nite_wealth

                                nitewealth
ToName
Baker Street                      47314290
Bayswater                         29131730
Bond Street                       25569630
Charing Cross                    105528410
Covent Garden                      7977010
Edgware Road (Bak)                10428880
Edgware Road (Cir)                18651020
Embankment                        43932920
Great Portland Street              8688950
Green Park                        37016170
Hyde Park Corner                    885730
Lancaster Gate                    24768330
Leicester Square                  73148850
Maida Vale                        23966620
Marble Arch                       35571110
Marylebone                        32994830
Oxford Circus                     67403500
Paddington                       125586630
Piccadilly Circus                 66136070
Pimlico                           46277280
Queensway                         46350280
Regent's Park                       725440
Royal Oak                          9606010
St. James's Park                   5564790
St. John's Wood                   20059090
Temple                            12329400
Tottenham Court Road              52403090
Victoria                         334353500
Warwick Avenue                    26387440
Westbourne Park                    6790980
Westminster                       19376770

In [148]:
evening_wealth.join(nite_wealth).to_csv('./station_incomingwealth.csv')

In [149]:
badnames = evening_wealth.join(nite_wealth)

In [155]:
badnames.index = [n.strip() for n in badnames.index]

In [156]:
badnames.index

Index([u'Baker Street', u'Bayswater', u'Bond Street', u'Charing Cross',
       u'Covent Garden', u'Edgware Road (Bak)', u'Edgware Road (Cir)',
       u'Embankment', u'Great Portland Street', u'Green Park',
       u'Hyde Park Corner', u'Lancaster Gate', u'Leicester Square',
       u'Maida Vale', u'Marble Arch', u'Marylebone', u'Oxford Circus',
       u'Paddington', u'Piccadilly Circus', u'Pimlico', u'Queensway',
       u'Regent's Park', u'Royal Oak', u'St. James's Park', u'St. John's Wood',
       u'Temple', u'Tottenham Court Road', u'Victoria', u'Warwick Avenue',
       u'Westbourne Park', u'Westminster'],
      dtype='object')

In [158]:
badnames.to_csv('./station_incomingwealth.csv')